### ISSUE TITLE
why this "_children" object?

### ISSUE THREAD

**Issue by ashokc** [confluentinc/kafka-connect-elasticsearch#10]
I am trying to put this connector to use in a situation where a number of Logstash agents would send their events to Kafka, and this connector would pump them into Elastic and so available on a Kibana dashboard... The json messages/events vary a great deal so I do not want any rigid schemas. Here is what I have done as a simple test

(1) start up ZK & Kafka the usual way

(2)

./bin/connect-standalone etc/test-connect-standalone.properties etc/kafka-connect-elasticsearch/test-elasticsearch.properties 

test-connect-standalone.properties has been modified so:

**key.converter.schemas.enable=false
value.converter.schemas.enable=false**

Without the above I get errors about 'json deserialization...'

test-elasticsearch.properties has been modified so (not sure if  needed to actually)

**schema.ignore=true**

(3) As I pump messages into Kafka (via Logstash) they do come up in the elastic index. But unfortunately the simple json that Logstash puts together ends up under a '_children' sub object !! This means that Kibana does not find the '@timestamp' field to work seamlessly...

...
 "_score": 1,
        "_source": {
          "_children": {
            "f1": {
              "_value": "value1"
            }
          },
...

The whole real json message sits under this '_children' sub object. Is there a configurable way to get rid of this '_children' tag and put the message directly under '_source' ?

Thanks
Ashok

**Comment by Ishiihara** [comment]
@ashokc Thanks for reporting this. I think this is related to how jest client handles the index request. I will take a look at this.

**Comment by Ishiihara** [comment]
@ashokc It turns out that the Elasticsearch HTTP client takes string instead of JsonNode. I have submitted a PR https://github.com/confluentinc/kafka-connect-elasticsearch/pull/11 to fix the issue.

**Comment by ashokc** [comment]
Thanks for looking into this Liquan! A seamless 1-1 integration like

Kafka Message => CONNECTOR => Elastic Doc

with no altering/processing of the message in any way by the connector
would be great with all the auto scaling that the connectors offer

Ashok

Ashok Chilakapati
Data Exploration <http://xplordat.com>
     - for fun & profit
