### ISSUE TITLE
Installing kafka-connect-elasticsearch - what extra jars are needed

### ISSUE THREAD

**Issue by martinhynar** [confluentinc/kafka-connect-elasticsearch#104]
Hi,

maybe stupid question, but I have problems installing this connector to kafka as its dependencies are missing in the libs folder. I built kafka-connect-elasticsearch 3.2.1 version myself and copied to libs, however starting it up gives me ClassNotFoundException (repeatedly). I added non-test dependency jest-2.0.0 which is defined in pom.xml, but for the rest I need to go one-by-one exception and find the corresponding jar (taking last jar version available). Is this 'the way' to install this connector, or is it described somewhere?

Thanks for help!

Worth mentioning, I am installing to vanilla Kafka 2.12-0.10.2.1

**Comment by rhauch** [comment]
What are the steps you used to install the connector?

**Comment by martinhynar** [comment]
Cloned kafka-connect-elasticsearch repo, fired maven build and copied kafka-connect-elasticsearch.jar to kafka libs folder.

**Comment by rhauch** [comment]
It's a little confusing, but after you build the connector there are a number of things in the `target` directory. The `kafka-connect-elasticsearch-<version>.jar` is only the JAR file with the connector code, but that doesn't include all the libraries. One of those directories in the `target` directory, namely `target/kafka-connect-elasticsearch-*-development/share/java/kafka-connect-elasticsearch/`,  does contain all the libraries. Add this directory to the Kafka Connect worker's classpath, or copy all of those JAR files into a directory that is already on the classpath.

**Comment by rhauch** [comment]
Since the existing connector build does provide the JARs, I'm going to close this issue since there's nothing to do. If you disagree, feel free to reopen and state why.

**Comment by martinhynar** [comment]
Hi, thanks for explanation. For the record, I instead switched to Confluent OSS that has all necessary libs included (and more).
