### ISSUE TITLE
How to change log level?

### ISSUE THREAD

**Issue by chaokunyang** [confluentinc/kafka-connect-elasticsearch#109]
I'm using kafka-connect-elasticsearch for my search framework indexer backend. How to change log level to view more log.? For example, change log level form "INFO" to "DEBUG". Is there a way to to this by updata connector config or provide an rest endpoint to change loglevel online? 
I'm using confluent 3.2.1.

**Comment by ewencp** [comment]
Logging is a worker-level configuration, so there's no way to set it per connector instance. To adjust the log levels you'd modify the connect-log4j.properties file and restart your worker.

**Comment by chaokunyang** [comment]
Ok, thanks
