### ISSUE TITLE
Is the connector able to perform date-based indexing?

### ISSUE THREAD

**Issue by cmpsoares91** [confluentinc/kafka-connect-elasticsearch#113]
Hello,

Logstash has the possibility to perform date-based indexing as is recommended by Elastic to make it easier and more efficient to manage the capacity of the cluster.

Does the connector have this ability as well or can it be developed?

Kind regards,
Carlos SOARES.

**Comment by rmoff** [comment]
Yes, using [SMT](http://kafka.apache.org/documentation.html#connect_transforms)s, you can do this. Here's an example of the config to add to your connector: 

```json
"transforms": "ts-to-topic",  
"transforms.ts-to-topic.type": "org.apache.kafka.connect.transforms.TimestampRouter"
```

If you want to specify the timestamp format and/or index pattern name: 

```json
 "transforms":"routeTS",  
 "transforms.routeTS.type":"org.apache.kafka.connect.transforms.TimestampRouter",  
 "transforms.routeTS.topic.format":"kafka-${topic}-${timestamp}",  
 "transforms.routeTS.timestamp.format":"YYYYMM"
```
