### ISSUE TITLE
The ES id issue when switch to the new kafka cluster

### ISSUE THREAD

**Issue by UCSBGauchos** [confluentinc/kafka-connect-elasticsearch#118]
Currently I use KAFKA_TOPIC+PARTITION_ID+KAFKA_OFFSET (for example, events+0+12333) as the elasticsearch ID. But when I do the cluster migration, the new kafka offset will start from 0 again. So the new coming data will override the old one because the new coming es id will override the old one. 

Is that any way to solve this issue?

**Comment by UCSBGauchos** [comment]
Just saw some message from #97 But I want to confirm that where I should add such transformation for kafka topic. In the kafka's connect-file-source.properties or the kafka-es-connector's config file?
`transforms=Rename
transforms.Rename.type=org.apache.kafka.connect.transforms.RegexRouter
transforms.Rename.regex=(.*)
transforms.Rename.replacement=prefix-$1` 

Thanks

**Comment by levzem** [comment]
@UCSBGauchos SMT configs should be added to the connector configs

Closing but feel free to reopen if you have any questions
