### ISSUE TITLE
TimeStampRouter creates in correct date timestamp 19691231/19701231

### ISSUE THREAD

**Issue by spavinashkumar** [confluentinc/kafka-connect-elasticsearch#121]
I am using TimeStampRouter in Kafka Connect Elastic search sink connector to create indices on daily basis. PFB the configuration which i am using. It is able to create index and pushes the data but the problem is the index gets created with default date value 19691231 and it is not getting created with current date.

{
  "transforms.Router.type": "org.apache.kafka.connect.transforms.TimestampRouter",
  "transforms.Router.timestamp.format": "yyyyMMdd",
  "transforms.Router.topic.format": "data-${topic}-${timestamp}",
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "name": "datesink-es",
  "topics": "dest_rev",
  "transforms": "Router",
  "connection.url": "http://172.16.0.47:9200,http://172.16.0.242:9200",
  "type.name": "rev",
  "key.ignore": "true",
  "schema.ignore": "true",
  "topic.key.ignore": "true",
  "topic.schema.ignore": "true"
}

data-dest_rev-19691231

**Comment by yuancheng-p** [comment]
Hi @spavinashkumar, I had the same issue. You need to feed the timestamp of your messages. This timestamp can either be fed from the producer, or by setting `log.message.timestamp.type` to `LogAppendTime` if you want the time when the message is written to the kafka topic.

**Comment by spavinashkumar** [comment]
Thanks Yuancheng! It is working now.
