### ISSUE TITLE
Use a data field to change elastic index output

### ISSUE THREAD

**Issue by BDeus** [confluentinc/kafka-connect-elasticsearch#123]
Hi,
is it possible to use the value of a field and the timestamp to set the topic name with ?
ex :
```
 {
"id":"123456",
"partition":1234
"foo":"bar"
}
```

-> topic like : mytopic-${partition}-yyyy.MM.dd?

Thanks

**Comment by BDeus** [comment]
i tried with RegexRouter but i don't know if there is a possibility to extract a field to use only in routing.
i don't know if it is possible to cumulate RegexRouter and TimestampRouter

**Comment by levzem** [comment]
@BDeus 

it is possible to chain transformations together. See [here](https://docs.confluent.io/current/connect/transforms/extractfield.html#extractfield) for an example on how to do that.

I will close this but feel free to reopen if you have further question
