### ISSUE TITLE
Issues while using AWS ES

### ISSUE THREAD

**Issue by UCSBGauchos** [confluentinc/kafka-connect-elasticsearch#125]
We sometimes have an error raised by connector: unknown ES hostname (we use AWS ES domain). We run it in kubernetes.

**Comment by saeedansari** [comment]
What have you done about this problem? We are planning to use this connector exactly the way you are using it. Kube + AWS.

I appreciate your suggestions.

**Comment by levzem** [comment]
@UCSBGauchos @saeedansari is this still an issue?

**Comment by levzem** [comment]
closing but feel free to reopen if you still need help
