### ISSUE TITLE
Byte type default value doesn't supported by ElasticSearch

### ISSUE THREAD

**Issue by vbeskrovnov** [confluentinc/kafka-connect-elasticsearch#132]
When we tried to insert `null_value` for binary datatype we get the following message from ElasticSearch: 
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [bytes] has unsupported parameters:  [null_value : AQ==]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Mapping definition for [bytes] has unsupported parameters:  [null_value : AQ==]"
  },
  "status": 400
}
```
It happens because of binary type in ElasticSearch has no `null_value` parameter: https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html
So, we should not set default value to this type here:
`io/confluent/connect/elasticsearch/Mapping.java:180`
```
case ElasticsearchSinkConnectorConstants.BINARY_TYPE:
  defaultValueNode = JsonNodeFactory.instance.binaryNode(bytes(defaultValue));
  break;
```

**Comment by purbon** [comment]
fixed by the merge of #302
