### ISSUE TITLE
java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.Long while setting default date value

### ISSUE THREAD

**Issue by vbeskrovnov** [confluentinc/kafka-connect-elasticsearch#134]
If we want to set default value for date field in schema, we should use following for example:
`Date.builder().defaultValue(new java.util.Date()).build()`
We can pass only  `java.util.Date` in `Date.builder().defaultValue()`, because there is validating in `org.apache.kafka.connect.data.ConnectSchema#validateValue(java.lang.String, org.apache.kafka.connect.data.Schema, java.lang.Object)`, where we compare value type with expecting type(In this case - `java.util.Date`).
But when json is created here `io/confluent/connect/elasticsearch/Mapping.java:182`
```
case ElasticsearchSinkConnectorConstants.DATE_TYPE:
  defaultValueNode = JsonNodeFactory.instance.numberNode((long) defaultValue);
  break;
```
This date value tried to cast to long and failed with 
`java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.Long`
So, we should do something like that:
`defaultValueNode = JsonNodeFactory.instance.numberNode(((java.util.Date) defaultValue).getTime());`

**Comment by omervk** [comment]
@levzem I've hit this issue too and would love for it and the PR @vbeskrovnov sent in to get some love from Confluent :)

**Comment by levzem** [comment]
@omervk looking into this

**Comment by levzem** [comment]
@omervk the PR is now in review - hopefully it will be merged soon :) and it will make into the 5.4 release

**Comment by omervk** [comment]
@levzem Thanks for taking this! Looking forward to seeing this released :)

Any idea what the timeline is for 5.4?

**Comment by cyrusv** [comment]
Resolved with https://github.com/confluentinc/kafka-connect-elasticsearch/pull/135

**Comment by levzem** [comment]
@omervk 5.4 is planned and upcoming but I cannot comment on exact timelines

**Comment by omervk** [comment]
Makes sense. Thanks for pushing this through, @levzem! Really appreciate it :)

Where would you recommend I watch for the official release?

**Comment by levzem** [comment]
We usually make a [blog post](https://www.confluent.io/blog/introducing-confluent-platform-5-3) for each release

**Comment by omervk** [comment]
Thanks :)
