### ISSUE TITLE
Re-indexe all the kafka topic after rebooting the elasticsearch connector

### ISSUE THREAD

**Issue by yuancheng-p** [confluentinc/kafka-connect-elasticsearch#140]
After restarting the elasticsearch connector, it tries to re-index all the existing data from the kafka topic (we see from elasticsearch monitoring that it has a very high speed of indexation, but the number of documents does not increase). As there are also incoming data going on, it takes very long time (more than 2 hours) before the elasticsearch connector could catch the most recent data. It seems it forgets the offset it committed.

Is this behavior intended to guarantee the exactly once or it comes from an configuration issue in the kafka / kafka connect ?

**Comment by zzbennett** [comment]
Possibly related to: https://github.com/confluentinc/kafka-connect-elasticsearch/issues/94

**Comment by yuancheng-p** [comment]
@zzbennett thanks for pointing out. Yes, it's the same issue.
