### ISSUE TITLE
Some errors while using the kafka-es connect

### ISSUE THREAD

**Issue by UCSBGauchos** [confluentinc/kafka-connect-elasticsearch#144]
The errors raised from org.apache.kafka.connect.errors.ConnectException: Bulk request failed:
failed to parse [data.start]
illegal_argument_exception, reason: Invalid format: NaN-NaN-NaNTNaN:NaN:NaN+NaN:NaN. 

This [data.start] should be timestamp. Just wondering why the connect can know it is invalid format because we dont't have schema information here. Can we ignore this error?

**Comment by levzem** [comment]
@UCSBGauchos this error is because your timestamp is improperly formatted according to Elasticsearch

Feel free to reopen if you have further questions but I will close this because its old
