### ISSUE TITLE
connector getting stopped when wrong message arrived

### ISSUE THREAD

**Issue by ramkuvel** [confluentinc/kafka-connect-elasticsearch#146]
I am using kafka elastic search connector with the below configurations:

**elasticsearch.properties**
---------------------------
name=ElasticsearchSinkConnector
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
topics=logging-integration
tasks.max=1
type.name=kafka-connect
connection.url=http://hostname:9200
topic.index.map=logging-integration:logging-integration
topic.key.ignore=true
topic.schema.ignore=true
schema.ignore=true
key.ignore=true

**connect-standalone.properties**
----------------------------------
bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000

When a wrong message arrives, ES connector is getting stopped. How do i resolve this?

When i tried to start the connector, getting the below message:
**bin/connect-standalone /tmp/connect-standalone.properties /tmp/elasticsearch.properties > logs/kafka-connect-elasticsearch.log**
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/apps/confluent/share/java/kafka/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/apps/confluent/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Nov 09, 2017 5:06:51 AM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

Please advise.

**Comment by ramkuvel** [comment]
Can i have an update please?

**Comment by saeedansari** [comment]
What do you mean by wrong message? Is your message not valid based on schema?

**Comment by ramkuvel** [comment]
Say message which is not in the same format of what is configured in Elasticsearch index, is arrived in kafka topic, Kafka ES connector is getting stopped. Post restarting the connector, getting the below message:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/apps/confluent/share/java/kafka/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/apps/confluent/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Nov 09, 2017 5:06:51 AM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

**Comment by ramkuvel** [comment]
Can i please have an update?

**Comment by saeedansari** [comment]
In your connector settings you have `topic.schema.ignore=true` whereas it should be list of topics you would like to ignore schema for. so it should be `topic.schema.ignore=[logging-integration]` in your case.

**Comment by synhershko** [comment]
Probably related: https://github.com/confluentinc/kafka-connect-elasticsearch/issues/147#issuecomment-357499523

**Comment by levzem** [comment]
@ramkuvel the above answer is correct. either specify only `topic.schema.ignore=logging-interaction` or `schema.ignore=true`

I am going to close this because a solution was provided and a significant amount of time has gone by. Feel free to reopen if this is still an issue.
