### ISSUE TITLE
Better solution for handling Elasticsearch indexing errors

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-elasticsearch#147]
Indexing requests into Elasticsearch can fail for many, many reasons, most of which are related to `mapper_parsing_exceptions`. These happen regularly when using Elasticsearch as a sink for log data that does not have a predefined schema. Although Elasticsearch has a [`ignore_malformed` config](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html), it does not actually [cover that many cases](https://github.com/elastic/elasticsearch/issues/10070). 

I've been using the ES connector to index log data (among other kinds of data), and the connectors that handle log data will crash whenever they encounter an exception like this, such as [this one](https://stackoverflow.com/questions/47170067/elasticsearch-need-workaround-for-not-being-able-to-index-docs-with-fields-tha). There's no easy way to make the connector skip the data, and there's no way to tell Elasticsearch to ignore the issue. There currently doesn't seem to be any good way to work around these issues. I've resorting to creating custom single message transforms that will format the data so as to not provoke Elasticsearch, but this is tedious, hacky and not a good long-term solution. I could set up stream processors the clean the data, but the topics going to Elasticsearch also go to other systems, so it's not the greatest solution.

I don't know what kind of solution should go into the ES connector but I have a few ideas:
1. Add a config that allows mapper parsing exceptions to be logged and ignored (like the `drop.invalid.message` config)
2. Add a fail handler mechanism where users can deploy their own custom fail handlers so they can decide what to do in these situations
3. Add a deferral mechanism where failed events can go into some kind of separate special index.
4. `mapper_parsing_exceptions` almost always specify the field that caused the issue. The field can be parsed out of the message and stripped from the document and then re-indexed.

In my years of working with ES, the way I've handled this in the past was with option 4. I'm currently hacking together option 2, but it feels limited and complex. Option 1 is the simplest, so I'd be happy to submit a PR to make that happen, but I want to see what the maintainers think first.

**Comment by zzbennett** [comment]
I coded up option 1 here: https://github.com/confluentinc/kafka-connect-elasticsearch/pull/148 It feels reasonable to me, but I'm definitely open to feedback.

**Comment by cvuillemez** [comment]
Agree with that. I can't use the connector for now, cause I put in Kafka many logs from various sources, and I don't have control on it. So ES exceptions like "illegal_argument_exception",  "invalid_type_name_exception" or "mapper_parsing_exception" occurs very frequently .

**Comment by synhershko** [comment]
A better way, and a more Elasticsearch'y way of doing that, is to split different data schemas to different indexes (possibly bearing the same prefix - and that will make it invisible to consumers like Kibana etc). I'd highly recommend NOT ignoring mapping errors, especially not with modern Elasticsearch instances. They simply indicate you are writing different types of data to the same schema, which eventually will mean you are losing data on writes.

Also see https://github.com/confluentinc/kafka-connect-elasticsearch/issues/154#issuecomment-357499243

**Comment by zzbennett** [comment]
Sure, @synhershko I definitely agree that your suggestion is the better way to handle mapping conflicts. If it's feasible for one's use case, I absolutely recommend having a predefined schema, handling conflicts explicitly and not dropping the invalid messages. Thanks for your comment, it's good to be clear about when this feature might be necessary.

My current use case (and this is a fairly common ELK use case), is this: I am maintaining an ELK stack that is for internal use at my company for engineers to analyze their application log data. I have no control over what data they send to ES and mapping conflicts happen occasionally. The way the ES connector is written now, there is actually _no way_ to get past these mapping conflicts. The connector will crash when it runs into one, and has no mechanism for deferring the event, or renaming the conflicting fields, or any other solution. So yeah, ideally the mapping conflicts should never happen, but when they inevitably do, there needs to be some way to deal with them that's easier than manually advancing the consumer offset in zookeeper, or having to manually tweak the ES indexes to accommodate the conflict and re-index the original index (and sometimes even this is not possible). Simply dropping the messages is too extreme for most use cases, but the ES connector needs some way to deal with the invalid messages.

**Comment by levzem** [comment]
closing because #148 was merged
