### ISSUE TITLE
Artifact in repo?

### ISSUE THREAD

**Issue by mmolimar** [confluentinc/kafka-connect-elasticsearch#15]
I can't download the artifact from Confluent's Maven repo (version 3.0.0). Is it uploaded?
[This](http://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/3.0.0/kafka-connect-elasticsearch-3.0.0.jar) is the URL from which I'm trying to connect.

**Comment by ewencp** [comment]
@mmolimar This connector was not available in the 3.0.0 release. We just opened up the repository last week to allow people to test it out and give feedback, but it won't be in an official CP release until CP 3.1.0. However, it is compatible with the 3.0.0 release, and we've included a [branch](https://github.com/confluentinc/kafka-connect-elasticsearch/tree/0.10.0.0) which should make it trivial to build against that version. Using `mvn package` will collect everything in the familiar layout from CP packages so you can zip it up and deploy it easily.

**Comment by mmolimar** [comment]
Ok @ewencp 
Many thanks for the info!
