### ISSUE TITLE
Fail to create indexes with TimestampRouter

### ISSUE THREAD

**Issue by stefanofrigerio** [confluentinc/kafka-connect-elasticsearch#152]
Hi,
with a cfg like this one 

```
topic.index.map=phoenix-to-elastic:phoenix
type.name=phoenix_service
transforms : Daily
transforms.Daily.type : org.apache.kafka.connect.transforms.TimestampRouter
transforms.Daily.topic.format : phoenix-${timestamp}
transforms.Daily.timestamp.format : yyyyMMdd
```
the Connect seems unable to create an index. It creates an index named 'phoenix', with or without the cfg 'topic.index.map', but when the first batch of messages are going to be delivered ES throws an error 
```java
[2017-11-22 16:55:02,273] ERROR Task phoenix-elasticsearch-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:455)
org.apache.kafka.connect.errors.ConnectException: Cannot create mapping <**MAPPING_HERE**>"resource.id":"phoenix-20171122","index":"phoenix-20171122"}],"type":"index_not_found_exception",**"reason":"no such index"**,"resource.type":"index_or_alias","resource.id":"phoenix-20171122","index":"phoenix-20171122"}}
	at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:65)
	at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:201)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:119)
```
it seems that `writer.createIndicesForTopics(topics);` is called _before_ the index name remapping.

**Comment by stefanofrigerio** [comment]
with Confluent 4.0.0 the problem still persists.

**Comment by tstitescardinal** [comment]
Hi @stefanofrigerio,
I was able to recreate the same error you are seeing with the regexRouter on a local vm install of Confluent 3.2.2.1 (including Schema Registry) and Elasticsearch 5.6.

As a work around, try adding "schema.ignore=true" to the Elasticsearch sink connector config.
I found that the regexRouter works when schema.ignore=true but will create an empty index with the original topic name. So if the topic name is "myTopic" and we _regexRouter_ that to "myTopic_regexed" then you will have two indices.
1. myTopic (no documents)
2. myTopic_regexed

You should be able to delete the empty index after starting your connector without any problems. 

Here is my config...

`{
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "type.name": "string_as_keyword",
  "topics": "myTopic",
  "tasks.max": "1",
  "transforms.rr.type": "org.apache.kafka.connect.transforms.RegexRouter",
  "batch.size": "2000",
  "transforms": "rr",
  "max.retries": "5",
  "max.in.flight.requests": "5",
  "key.ignore": "false",
  "retry.backoff.ms": "100",
  "max.buffered.records": "20000",
  "schema.ignore": "true",
  "flush.timeout.ms": "10000",
  "transforms.rr.replacement": "$1_regexed",
  "topic.key.ignore": "",
  "name": "smt_es_sink",
  "connection.url": "http://localhost:9200",
  "transforms.rr.regex": "(.*)",
  "linger.ms": "1",
  "topic.schema.ignore": ""
}`

*  "type.name": "string_as_keyword" is the mapping I am using but a mapping doesn't need to exist prior to creating and starting the connector.

Hope this helps!

**Comment by rmoff** [comment]
Same issue as #99

**Comment by levzem** [comment]
issue #99 was resolved so closing this as it is duplicate
