### ISSUE TITLE
On start up connector throws  "resource_already_exists_exception" for an index 

### ISSUE THREAD

**Issue by TattiQ** [confluentinc/kafka-connect-elasticsearch#155]
Hello! 
I am testing the elastic sink connector and upon restart it throws 
kafka-elastic connect-standalone: org.apache.kafka.connect.errors.ConnectException: Could not create index 'test-application': {"root_cause":[{"type":"resource_already_exists_exception", 

On startup, the connector checks for the existence of an index and fails  ,thus it tries to create a new one with the same name. I assume HEAD request on the index returns 404. 

elastic code: 
https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/indices/IndicesExists.java 

Looks like the issue is connected to the fact that credentials are used in connection string here. With no auth at all, the issue is not reproduced.  

connector is set up as follows 

name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topic.index.map=application:application-0
topics=application
key.ignore=true
connection.url=http://kafka:pass@elastic:9200
type.name=app
schema.ignore=true 

I wonder if this would/could  be somehow worked around in confluent sink connector code?  
I am grateful for any thoughts on this.  
Thanks in advance.

**Comment by TattiQ** [comment]
could i be that it had to do with the fact that there are credentials specified in the connection url? ..

**Comment by TattiQ** [comment]
The issue is  not reproduced if I set up a test elastic with no auth and direct sink to it. Is there really no way to use connection string with creds in it  for it to work properly?

**Comment by levzem** [comment]
@TattiQ 

you can use the configs `connection.username` and `connection.password` for authentication instead of passing it in the url 

let me know if you are still having this problem
