### ISSUE TITLE
No handler for type [string] declared on field [after]"}]

### ISSUE THREAD

**Issue by vlad1777d** [confluentinc/kafka-connect-elasticsearch#160]
Hello.
If in topic, which this connector reads, there are some records with type: string, it throws an error:
> No handler for type [string] declared on field [after]"}]

(because Elasticsearch 6 dropped support for 'string')

If to rename it into 'text' - it'll throw such error:
> org.apache.kafka.connect.errors.DataException: Unknown schema type: text

I'm using JSON serializer:
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

If to use AVRO serializer - all would be normal, but than I would have issues while decoding it in Javascript.

Is there any way to make it sending messages to elasticsearch?
Thanks.

**Comment by synhershko** [comment]
Please see https://github.com/confluentinc/kafka-connect-elasticsearch/issues/154#issuecomment-357499243

**Comment by vlad1777d** [comment]
@synhershko , understood, thank you.

**Comment by rayokota** [comment]
This is fixed with #169
