### ISSUE TITLE
Cannot build because of "Non-resolvable parent POM"

### ISSUE THREAD

**Issue by vlad1777d** [confluentinc/kafka-connect-elasticsearch#161]
I cloned repository, and when making "mvn build" I have such output:
https://pastebin.com/9TGfzmyb

I want to change 'string' type to 'text' because of this issue:
https://github.com/confluentinc/kafka-connect-elasticsearch/issues/160

**Comment by jrs360** [comment]
Also getting the same build error.

**Comment by kkonstantine** [comment]
If you are building a `SNAPSHOT` version of the connector locally you'll need to checkout, build and install locally a few additional repos on the equivalent snapshot version as well. 

Usually the FAQ page in every connector maintains a list of such dependencies. For the ES connector read here: https://github.com/confluentinc/kafka-connect-elasticsearch/wiki/FAQ

If a repo is missing from the list (as was the case above for `common` that was added recently as a connector's dependency) you should be able to find it by searching the list of confluentinc repos here: https://github.com/confluentinc

**Comment by jrs360** [comment]
Thank you for the reply.

I need to incorporate pull request #77 (or #112, same thing) to support basic authentication. Is there an ETA when this capability will be in the native connector?
