### ISSUE TITLE
add config option for kafka url string

### ISSUE THREAD

**Issue by nhjiejan** [confluentinc/kafka-connect-elasticsearch#164]
im guessing the default kafka location is localhost:9092, is there an option to change this?

**Comment by cricket007** [comment]
Yes, that's the default. The bootstrap servers need to be set for any Kafka Connect, not just Elasticsearch

https://docs.confluent.io/current/connect/userguide.html#configuring-workers

**Comment by rhauch** [comment]
Closing this since it's a question.
