### ISSUE TITLE
issue with kafka-connect-mqtt while connecting with MQTT broker using username and password

### ISSUE THREAD

**Issue by tamilhce** [confluentinc/kafka-connect-elasticsearch#167]
The kafka-connect-mqtt(installed using the jar:afka-connect-mqtt-1.0.0-1.0.0-all.jar)  works fine with anonymous connection(without user-name&password).
While connecting with MQTT broker with user-name & password authentication, In broker trace log it clearly shows that kafka-connect-mqtt couldn't pass the configured  user-name & password.
I have verified with MQTT client manually, there is no issue with broker and the issue is from kafka-c
onnect-mqtt. Attached the logs for your reference.

[mqtt-source_debugging.txt](https://github.com/confluentinc/kafka-connect-elasticsearch/files/1655847/mqtt-source_debugging.txt)

**Comment by rhauch** [comment]
@tamilhce, it looks like perhaps you meant to log this in a different repository. I'm going to close thi -- if this does somehow relate to the Elasticsearch Connector, please provide more details as to how. Thanks!
