### ISSUE TITLE
Parse Json data before writing to Elasticsearch

### ISSUE THREAD

**Issue by ngwwm** [confluentinc/kafka-connect-elasticsearch#170]
Hi, 
We tried and be able to sink data to ES successfully. Below is the data in ES.
      {
        "_index" : "devicedata",
        "_type" : "kafka-connect",
        "_id" : "iot-devicedata+0+3107",
        "_score" : 1.0,
        "_source" : {
          "gateway_id" : "B8:27:EB:F7:52:10",
          "gateway_ip" : "10.0.0.1",
          "device_id" : "B0:49:5F:02:6F:B5",
          "device_type" : "blood_pressure",
          "jdata" : "{\\"patientid\\":\\"5678\\",\\"systolic\\":104,\\"diastolic\\":70,\\"pulserate\\":91}",
          "data_timestamp" : "2018-02-02 17:03:02"
        }
      }

You can see that "jdata" is a string in json format. The source data is from vendor and we can't change it. So, I would like to see if there is a way the connector can parse, convert and update it before writing to ES.

Regards,
wwm

**Comment by kccheung** [comment]
@cricket007 Thanks! You saved my life! I have been struggle for days to figure out how to handle this...

**Comment by ngwwm** [comment]
Having read the readme, I have no idea on how to get started. Is there any step by step Installation/configuration guide?

**Comment by cricket007** [comment]
@ngwwm That should be answered at https://github.com/Landoop/kafka-connect-kcql-smt/issues/5

But short answer: Build it with Gradle, as shown in the README, add to the `CLASSPATH` of `kafka-connect` java process.

**Comment by hongphu8790** [comment]
Hi @cricket007,

Does KCQL support create new struct based on field contains json string? I tried KCQL, but it only flatten field in this case.

**Comment by cricket007** [comment]
@hongphu8790

I've not used it, but according to this table, a Struct type will only be output if the input is also a Struct 

https://github.com/Landoop/kafka-connect-kcql-smt/blob/master/README.md#kafka-connect-payloads-supported
