### ISSUE TITLE
not enough master nodes discovered during pinging

### ISSUE THREAD

**Issue by drmjbb** [confluentinc/kafka-connect-elasticsearch#172]
I am seeing this error, 

not enough master nodes discovered during pinging (found [[Candidate{node={........, clusterStateVersion=-1}]], but needed [2]), pinging again

I am using _https://github.com/Landoop/helm-charts/blob/master/charts/kafka-connect-elastic5s-sink_

**Comment by jcustenborder** [comment]
@drmjbb Looks like you are in the wrong repo. https://github.com/Landoop/stream-reactor/tree/master/kafka-connect-elastic5
