### ISSUE TITLE
No /tmp/connect.offsets on my file system

### ISSUE THREAD

**Issue by yangboufo** [confluentinc/kafka-connect-elasticsearch#176]
I start a connector in standalone mode, but I cannot find the /tmp/connect.offsets file under /tmp.

**Comment by jcustenborder** [comment]
@yangboufo This is part of the configuration of the connect worker process. This is not relevant to this project. Take a look at [Connect Configuration Documentation](https://kafka.apache.org/documentation/#connectconfigs) on the Apache Kafka web site. `offset.storage.file.filename` is the worker property you need to configure.
