### ISSUE TITLE
Data does not appear in Elasticsearch

### ISSUE THREAD

**Issue by cxk280** [confluentinc/kafka-connect-elasticsearch#183]
I'm building a simple chat app to practice my abilities with Kafka and Elasticsearch. I'm using Confluent's Kafka and Kafka Connect Elasticsearch Connector as well as the [open source version](https://www.elastic.co/products/elasticsearch) of Elasticsearch. Communications between my app and Kafka use the Kafka-rest API with JSON. I am following the instructions [here](https://docs.confluent.io/current/connect/connect-elasticsearch/docs/elasticsearch_connector.html).

As the instructions state, I am running Elasticsearch before I start the rest of the process. So far I am able to send messages from the app to Kafka and back again with no problem. When I run confluent load elasticsearch-sink after sending messages, I get the output the instructions say to expect. I don't get that output if I haven't sent the messages, which seems to indicate that the flow of data is working at least that far. However, when I cURL with the following command, which the docs state should get my data from Elasticsearch...

`curl -XGET 'http://localhost:9200/jsontest/_search?pretty'`

...I get the following output...

```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

...which does not include my messages. The data should be in hits.hits.

Please note that I am using version 5.6.8 of Elasticsearch, as the Confluent docs state that there is a known issue with versions 6.x. Also, my cURL command differs slightly from the example to account for the fact that my topic is` jsontest`, not `test-elasticsearch-sink`. I have been sure to change the topics in the `quickstart-elasticsearch.properties` file in order for this to work.

How do I get my data into Elasticsearch?

**Comment by sheshmantha** [comment]
Hello - were you able to resolve this issue?  If so, how?  We are experiencing the same issue.

**Comment by cxk280** [comment]
No, I was unable to solve it. No one could figure it out on StackOverflow either. I ultimately decided to connect my app to ElasticSearch directly, sending the data after it had been returned from Kafka. I suspect this could cause some issues at scale, but my app was just a small portfolio project so it worked for me.

Too bad no one at Confluent is responding here...

**Comment by levzem** [comment]
@cxk280 and @sheshmantha 

apologies for the late reply! are you still experiencing issues?
