### ISSUE TITLE
Can not do mvn clean package

### ISSUE THREAD

**Issue by szxunchao** [confluentinc/kafka-connect-elasticsearch#204]
After git clone the source code, I tried to build it with mvn clean package. I encountered the following errors

jason@ubuntu:~/kafka-connect-elasticsearch$ sudo mvn package
[INFO] Scanning for projects...
[WARNING] Could not transfer metadata io.confluent:common:5.0.0-SNAPSHOT/maven-metadata.xml from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:[unknown-version]: Could not transfer artifact io.confluent:common:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 7, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:kafka-connect-elasticsearch:[unknown-version] (/home/jason/kafka-connect-elasticsearch/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:[unknown-version]: Could not transfer artifact io.confluent:common:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 7, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Anyone had the same error?

**Comment by johnzhanghua** [comment]
https://github.com/confluentinc/kafka-connect-elasticsearch/wiki/FAQ 

Run this 2 steps first will work.

Kafka - clone https://github.com/apache/kafka/ and build with ./gradlew installAll
Common library - clone https://github.com/confluentinc/common and build with mvn install

BTW, I don't know what's the purpose not putting this FAQ into the Readme, other than let others struggling building.

**Comment by pnabee** [comment]
http://packages.confluent.io/maven/  repo was not available then how will build like mvn clean package 

👎

**Comment by kkonstantine** [comment]
We don't publish snapshot version to a public maven repo. For development on a snapshot version, (e.g. master or a release branch such as 5.0.x, etc) please follow the instructions in the FAQ and checkout and build all the confluent project that HDFS connector has as dependencies (even transitive deps).

@johnzhanghua good point about readme, we had updated elsewhere, but not here. Updated now.
