### ISSUE TITLE
Load balancing between kafka and elasticsearch

### ISSUE THREAD

**Issue by imgroot1391** [confluentinc/kafka-connect-elasticsearch#208]
My connector between kafka and elasticsearch is working fine right now, I'm using the distributed mode amongst 3 nodes of kafka and 3 "nodes" of the kafka connector. When inserting a new sink via the REST API, you can assign a value to connection.url. I want to place a couple of elasticsearch data nodes in here in case one goes down so i don't have a single point of failure. The docs say that this value takes a list so I have attempted to place in:

 

>  "connection.url" : "http://10.10.120.4:9200,http://10.10.120.4:9200"

However, this did not work. I ran a status check on the connector and it reports that it has failed. I also tried:

> "connection.url" : ["http://10.10.120.4:9200,http://10.10.120.4:9200"]

This did not work either. Here is the error code when running that status check:
`curl -XGET -H 'Content-type:application/json' 'http://localhost:8083/connectors/cluster1_sink/tasks/0/status'`

> {"state":"FAILED","trace":"org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.connect.errors.ConnectException: Bulk request failed: [{\"type\":\"illegal_argument_exception\",\"reason\":\"[geoip.location] is defined as an object in mapping [true] but this name is already used for a field in other types\"}, {\"type\":\"illegal_argument_exception\",\"reason\":\"[geoip.location] is defined as an object in mapping [true] but this name is already used for a field in other types\"}]\n\tat io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:353)\n\tat io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:326)\n\tat io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:312)\n\t... 4 more\n","id":0,"worker_id":"10.10.100.5:8083"}

It looks like it is complaining about the mapping, however if I only place one node in the connection.url field, everything works. So I am confused by this.

Any help would be appreciated. Thank you

**Comment by rhauch** [comment]
What version of the Elasticsearch connector are you using? You should be able to define multiple ES endpoints as a single comma-separated string (spaces after comma are fine) in the JSON file. Something like:

    "connection.url" : "http://server1:9200,http://server2:9200"

The connector is basically doing the same thing that is described in [this StackOverflow post](https://stackoverflow.com/questions/45114596/how-to-pass-multiple-nodes-address-in-jest-elastic-search).

**Comment by bm1391** [comment]
I am using a older version because of build issues with ES 5.x. I am using 1.1. Might try and upgrade to a newer version...Thank you for that link. Any info on what that error message might mean?

**Comment by levzem** [comment]
@imgroot1391 do you still need help?
