### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hyitclj** [confluentinc/kafka-connect-elasticsearch#210]
I run         mvn clean package
the result as follows:
[INFO] Scanning for projects...
[WARNING] Could not transfer metadata io.confluent:common:5.0.0-SNAPSHOT/maven-metadata.xml from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:[unknown-version]: Could not transfer artifact io.confluent:common:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 7, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:kafka-connect-elasticsearch:[unknown-version] (/home/kafka/kafka-connect-elasticsearch-master/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:[unknown-version]: Could not transfer artifact io.confluent:common:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 7, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by cricket007** [comment]
Duplicates #204 

Checkout a tag for a released version, or see the wiki - https://github.com/confluentinc/kafka-connect-elasticsearch/wiki/FAQ

**Comment by kkonstantine** [comment]
We don't publish snapshot version to a public maven repo. For development on a snapshot version, (e.g. master or a release branch such as 5.0.x, etc) please follow the instructions in the FAQ and checkout and build all the confluent project that HDFS connector has as dependencies (even transitive deps).

See also: https://github.com/confluentinc/kafka-connect-elasticsearch/issues/204
