### ISSUE TITLE
Possible to start SinkTask/SourceTask for retry mechanism? 

### ISSUE THREAD

**Issue by lwu08** [confluentinc/kafka-connect-elasticsearch#224]
As in public class ElasticsearchSinkTask extends SinkTask, start(Map<String, String> props, ElasticsearchClient client) call may fail due to any connection issue... Is it possible to trigger re-running the task automatically? Basically want to know how to implement retry connecting mechanism inside kafka-connect framework. Thanks for help!

**Comment by shiva2991** [comment]
Kafka connect has retry mechanism, you can find that in jdbc connector sink task please have a look.

**Comment by levzem** [comment]
@lwu08 you can either throw a `RetriableException` and the framework will retry or catch the connection exceptions and retry manually yourself
