### ISSUE TITLE
unable to transform header to value

### ISSUE THREAD

**Issue by Divesht** [confluentinc/kafka-connect-elasticsearch#228]
hi, i am trying to follow the instructions as per https://cwiki.apache.org/confluence/display/KAFKA/KIP-145+-+Expose+Record+Headers+in+Kafka+Connect#KIP-145-ExposeRecordHeadersinKafkaConnect-ConvertingHeaderValues to convert headers to fields in ES. Below are my config files. Unable to see the headers in the ES records. Any help would be appreciated. thanks

####### connect-standalone.properties ######
bootstrap.servers=kafka-service:80
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
schemas.enable=false

########## elasticsearch-connect.properties ##########
`name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=5
topics=MY_TOPIC
topic.index.map=MY_TOPIC:my_topic
connection.url=http://elasticsearch:9200
type.name=dlq
key.ignore=true
schema.ignore=true

transforms=copyHeaderToValueField
transforms.copyHeaderToValueField.type=org.apache.kafka.connect.transforms.Flatten$Value
transforms.copyHeaderToValueField.field=failure_reason
transforms.copyHeaderToValueField.headers=failure_reason
transforms.copyHeaderToValueField.operation=copy`

I get a "Invalid value org.apache.kafka.connect.transforms.HeaderTo$Value for configuration transforms.copyHeaderToValueField.type: Class org.apache.kafka.connect.transforms.HeaderTo$Value could not be found" if i use the below setting in elasticsearch-connect.properties
transforms.copyHeaderToValueField.type=org.apache.kafka.connect.transforms.HeaderTo$Value

**Comment by eperinan** [comment]
Hi @Divesht 

Do you have any progress with that transformation?

**Comment by levzem** [comment]
@Divesht 
the HeaderToValue transformation mentioned in KIP-145 has not been implemented yet. I will close this but feel free to reopen if you have any questions.

**Comment by rajnijain7782** [comment]
Is it implemented now?

**Comment by viswa-optimusprime** [comment]
@levzem Is it implemented now?
