### ISSUE TITLE
Global config values for topic-overridable options should act as defaults

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-elasticsearch#23]
If I have 

    key.ignore=true

I get a failure: 

```
[pool-2-thread-1] ERROR org.apache.kafka.connect.runtime.WorkerSinkTask - Task elasticsearch-sink-0 threw an uncaught and unrecoverable exception
org.apache.kafka.connect.errors.DataException: STRUCTis not supported as the document id.
        at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:80)
        at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:134)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:308)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:129)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:381)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The config is definitely being picked up : 

```
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig - ElasticsearchSinkConnectorConfig values:
        type.name = kafka-connect
        batch.size = 2000
        max.retry = 5
        key.ignore = true
        max.in.flight.requests = 5
        retry.backoff.ms = 100
        max.buffered.records = 20000
        schema.ignore = false
        flush.timeout.ms = 10000
        topic.index.map = [ORCL.SOE.LOGON:soe.logon]
        topic.key.ignore = []
        connection.url = http://localhost:9200
        topic.schema.ignore = []
        linger.ms = 1
```

If I set the key ignore specifically for the topic: 

    topic.key.ignore = ORCL.SOE.LOGON

Then processing works fine. Should `key.ignore` work this way (globally) or am I misunderstanding it?

**Comment by rmoff** [comment]
With some [debug added](https://github.com/rmoff/kafka-connect-elasticsearch/commit/3731ea771c539002d12ca89afd8f8992510e4aa3) to DataConverter.java, shows that the ignoreKey global is not being honoured if a topic config exists for another config variable, such as index: 

`.properties` :

```
name=elasticsearch-sink-03
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
key.ignore=true
connection.url=http://localhost:9200
type.name=kafka-connect
# Custom config
topics=ORCL.SOE.LOGON
topic.index.map=ORCL.SOE.LOGON:soe.logon
```

```
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig - ElasticsearchSinkConnectorConfig values:
        type.name = kafka-connect
        batch.size = 2000
        max.retry = 5
        key.ignore = true
        max.in.flight.requests = 5
        retry.backoff.ms = 100
        max.buffered.records = 20000
        schema.ignore = false
        flush.timeout.ms = 10000
        topic.index.map = [ORCL.SOE.LOGON:soe.logon]
        topic.key.ignore = []
        connection.url = http://localhost:9200
        topic.schema.ignore = []
        linger.ms = 1
[...]
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.DataConverter - Topic found in topicConfigs
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.DataConverter - Config values: index soe.logon / ignoreKey false / ignoreSchema false
[pool-2-thread-1] ERROR org.apache.kafka.connect.runtime.WorkerSinkTask - Task elasticsearch-sink-03-0 threw an uncaught and unrecoverable exception
org.apache.kafka.connect.errors.DataException: STRUCT is not supported as the document id.
```

Note **`ignoreKey false`**, even though the global `key.ignore=true`

With explicit config of the ignoreKey for the topic:

`.properties` : 
```
name=elasticsearch-sink-03
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
key.ignore=true
connection.url=http://localhost:9200
type.name=kafka-connect
# Custom config
topics=ORCL.SOE.LOGON
topic.index.map=ORCL.SOE.LOGON:soe.logon
topic.key.ignore=ORCL.SOE.LOGON
```

```
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig - ElasticsearchSinkConnectorConfig values:
        type.name = kafka-connect
        batch.size = 2000
        max.retry = 5
        key.ignore = true
        max.in.flight.requests = 5
        retry.backoff.ms = 100
        max.buffered.records = 20000
        schema.ignore = false
        flush.timeout.ms = 10000
        topic.index.map = [ORCL.SOE.LOGON:soe.logon]
        topic.key.ignore = [ORCL.SOE.LOGON]
        connection.url = http://localhost:9200
        topic.schema.ignore = []
        linger.ms = 1

[...]
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.DataConverter - Topic found in topicConfigs
[pool-2-thread-1] INFO io.confluent.connect.elasticsearch.DataConverter - Config values: index soe.logon / ignoreKey true / ignoreSchema false
```

**Comment by rmoff** [comment]
This is where my non-existent Java understanding totally runs out :)
Is the way the config is being stored not taking into account the global ignoreKey setting, and if there is no topic-specific ignoreKey config provided defaulting to false? 
For now, is the fix to make sure that per-topic ignoreKey (and presumably ignoreSchema) is always specified if overriding the index mapping?

**Comment by shikhar** [comment]
@rmoff as you discovered the globals are not overriding the per-topic configuration if any topic-level override is present, but indeed they should be as that's the intuitive behavior. Thanks for reporting!

**Comment by shikhar** [comment]
This is fixed with #30

**Comment by ruchit31** [comment]
Class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector could not be found.

**Comment by ewencp** [comment]
@ruchit31 Is that related to this issue somehow? It looks like you have a `CLASSPATH` configuration problem since it is unable to find the class. Have you made sure the connector is on your `CLASSPATH`? Are you using Confluent Platform or your own build?

**Comment by ruchit31** [comment]
@ewencp can you elaborate about what do I need to include in classpath.
This is what I have in my 
classpath " /home/ec2-user/kafka-connect-elasticsearch/ "
Am I missing something ?

**Comment by ewencp** [comment]
@ruchit31 Is `/home/ec2-user/kafka-connect-elasticsearch/` just a clone of this repo? If so, you'd need to build the connector and the jars would be under `/home/ec2-user/kafka-connect-elasticsearch/target/kafka-connect-elasticsearch-3.5.0-SNAPSHOT-package/share/java/kafka-connect-elasticsearch/`. Also, you might be missing the `*` you need at the end of the path to indicate you want it to pick up all jar files in that directory.

**Comment by ruchit31** [comment]
@ewencp Thanks for the help, Actually my maven build is failing. 
No connector available to access repository confluent (${confluent.maven.repo}) of type default using the available factories WagonRepositoryConnectorFactory

I am trying to add wagon extension but it is giving me an error

<build>
    <extensions>
        <extension>
            <groupId>org.apache.maven.wagon</groupId>
            <artifactId>wagon-ssh</artifactId>
            <version>2.4</version>
        </extension>
    </extensions>
</build>

**Comment by rmoff** [comment]
@ruchit31 I answered your question here: https://stackoverflow.com/questions/45223398/i-am-not-able-to-connect-kafka-to-elastic-search-using-kafka-elasticsearch-conne. If you've got specific problems with the connector, best to raise them as a separate github issue, as this one is (a) closed and (b) unrelated to the problems you have.
