### ISSUE TITLE
Records deleted from Postgres aren`t being deleting in ES

### ISSUE THREAD

**Issue by kkstunts** [confluentinc/kafka-connect-elasticsearch#230]
I have setup streaming from Postgres to ES. 
INSERT and UPDATE works perfectly, but DELETE is not being executed in ES.
When a row is deleted in postgres, it show up in kafka topic as null.

**Comment by tranductri** [comment]
> When a row is deleted in postgres, it show up in kafka topic as null.

That is the value of the message only. In this case this is the tombstone message.

This is what I did to make it run.

1. Setup the all the stack with bellow example. 
https://github.com/debezium/debezium-examples/tree/master/unwrap-smt
They use MySQL as source but It should be fine with Postgres.

2. I upgraded version of kafka-connect-elasticsearch to 5.0.0 by change the path to get 5.0.0 package in https://github.com/debezium/debezium-examples/blob/master/unwrap-smt/debezium-jdbc-es/Dockerfile
(The delete operation in ES only available in version >= 4.0.x. You can check PR #165 )
replace : http://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/3.3.0/kafka-connect-elasticsearch-3.3.0.jar 
with http://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/5.0.0/kafka-connect-elasticsearch-5.0.0.jar

3. Update the sink config in https://github.com/debezium/debezium-examples/blob/master/unwrap-smt/es-sink.json to bellow setting.
`{
    "name": "elastic-sink",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "tasks.max": "1",
        "topics": "customers",
        "connection.url": "http://elastic:9200",
        "transforms": "unwrap,key",
        "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
        "transforms.unwrap.drop.tombstones": "false",
        "transforms.unwrap.drop.deletes": "false",
        "transforms.key.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
        "transforms.key.field": "id",
        "key.ignore": "false",
        "type.name": "customer",
        "behavior.on.null.values": "delete"
    }
}
`

There is 3 config you need to notice:
- "transforms.unwrap.drop.tombstones": "false" -> Ignore filter for tombstone message.
- "transforms.unwrap.drop.deletes": "false" -> Ignore filter for deletes message.
- "behavior.on.null.values": "delete" -> Enable behavior to delete in ES for null value message.
The reason I did that is here https://debezium.io/docs/configuration/event-flattening/

Try it and It may help you to understand.

Sorry for my bad English.

**Comment by purbon** [comment]
as @tranductri properly shares, if the message has a null payload the connector can issue a delete statement, this is a config option as you can see from https://github.com/confluentinc/kafka-connect-elasticsearch/blob/a97e2b048253c706bea80aa79aebfaa30a1d0424/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java#L142 , this is controller with the config variable ```behavior.on.null.values``` as shared previously.

closing this issue as is not really an issue of the connector. 

hope it helps,

**Comment by gunnarmorling** [comment]
As a reference for future readers: the Debezium [unwrap-smt example](https://github.com/debezium/debezium-examples/tree/master/unwrap-smt) has been updated and now also shows the right configuration for propagating deletes to Elasticsearch and JDBC-compatible databases.
