### ISSUE TITLE
Lag in data getting into elasticsearch from kafka

### ISSUE THREAD

**Issue by shiveshsky** [confluentinc/kafka-connect-elasticsearch#238]
I have logs coming into 1 topic of Kafka, I am parsing them and putting them into 2 separate Kafka topic(having 10 partitions each), thereafter I am putting them into elasticsearch via kafka-elastic sink using 10 tasks. But I am facing serious lag of about 10 minutes lag for 30 minutes of continuous logs which in-turn increases for more logs. Please suggest to narrow the gap.

Ps. I checked my parser works fine and puts the data into the 2 topics in no time. Also I am using latest elasticsearch 6 and kafka.

**Comment by purbon** [comment]
@shiveshsky I recommend you first an small sizing exercise of sizing where you put messages in one topic and then send them to elastic, there are many moving parts that can affect this lag, are you having too big messages? are you having network or stability issues in your brokers? I suggest you do this small sizing exercise and then scale up from there. Keep in mind as well problems could be as well on the ES side.

closing it for now as it does not look as a problem of the connector, feel free to reopen if new information shows up.

**Comment by sanjoyde** [comment]
I have two topics in Kafka, from one Logstash is listening. Kafka Producer is producing  the data and Logstash is sending the data to Elasticsearch, but using logstash when I am consuming it, after running 1 hrs I have seen that there is a 10 mins lags between the produced and consuming messaging in Elasticsearch. Per minute only 6 records being produced. My logstash conf file is:

input{
	kafka{
		bootstrap_servers =>"localhost:9092"
		topics => ["event_data"]
		
	}

}
filter 	{

			
	json{
		source => "message"
	}
        date {
	timezone => "UTC"
	match => ["timestamp","UNIX_MS"]
	target => "@timestamp"
}
}
output{
	elasticsearch{
		hosts => "localhost:9200"
		index => "event_data"
		
	}
} 
--------------------------------------------------
Not able to find out the issue. Please help, thanks.
