### ISSUE TITLE
Index creation ignores dynamic templates? 

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-elasticsearch#24]
If I create an [index template with dynamic mappings](https://gist.github.com/rmoff/4d57a815a539b9f34eeec1ed4cdf8ede), they are ignored if I start the connector from scratch, but honoured if the connector is already running and I delete the index and then create new data to force its recreation. 
I'll try and create a test case to reproduce, but is there something about how the connector initialises itself with Elasticsearch at startup that would explain this behaviour? 

thanks.

**Comment by rmoff** [comment]
If I set 

    topic.schema.ignore=myTopic

then the dynamic mappings are honoured. Is this the designed behaviour, and purpose of this configuration setting? Thanks.

**Comment by shikhar** [comment]
@rmoff yes this is indeed the designed behavior, the doc for `schema.ignore` is more informative than the per-topic `topic.schema.ignore`
