### ISSUE TITLE
auto creation of indexes and sinking for topic that follow a particular regex pattern

### ISSUE THREAD

**Issue by shiveshsky** [confluentinc/kafka-connect-elasticsearch#241]
Suppose I have topics being created in kafka
test1, test2,  test3 
I tried topics.regex but it only creates indices for topics already existing
How can I sink a new topic into an index when it gets created dynamically.

**Comment by levzem** [comment]
@shiveshsky I am not sure what you are exactly asking.

If you want to add a new topic and it matches the regex of the connector, it should automatically pick up and consume from that topic and correspondingly create an index for it as well.

**Comment by levzem** [comment]
closing but feel free to reopen if you have any questions still
