### ISSUE TITLE
Use Update or Insert API while creating new documents in Elasticsearch

### ISSUE THREAD

**Issue by purbon** [confluentinc/kafka-connect-elasticsearch#248]
Currently the connector only support two different actions while creating documents out of a Kafka topic:

- Index: create a new document for every event read from the topic. This operation will overwrite the document if the same ID is used, incrementing the version number.
- Delete: remove documents from the index when the connection find a tombstone event.

There is as well the use case of partially updating a document, might be interesting when the payload is big.

Links:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-update

**Comment by lukegil** [comment]
Is there any timeline on the PR for this issue? (https://github.com/confluentinc/kafka-connect-elasticsearch/pull/239)

Happy to lend a hand if there's anything blocking!

**Comment by shankao** [comment]
It would be nice to have this on 5.3 release as it seems to be a very useful feature

**Comment by JustinMoser** [comment]
Hi, was this ever implemented? There is a real need to update documents in ES based on incoming messages in Kafka not just create new documents.

**Comment by shankao** [comment]
It's in master, working for my project in prod. with 0 problems for 3 months. I think it's in 5.3+ also, so I'll switch to the stable release instead of build master :)

**Comment by JustinMoser** [comment]
@shankao do you know of any documentation on how UPSERT? How exactly does one configure this?

**Comment by shankao** [comment]
You may want this 2 if you want ES to mimic some source correctly:

"behavior.on.null.values": "delete",
"write.method": "upsert",

**Comment by shankao** [comment]
Well, that's for debezium sources though. Maybe it's ok for you with the upsert line only

**Comment by levzem** [comment]
closing because this has been implemented in #239
