### ISSUE TITLE
Allow messages in single topic to go to different indexes chosen at runtime

### ISSUE THREAD

**Issue by yonigibbs** [confluentinc/kafka-connect-elasticsearch#249]
Is it possible to choose the Elasticsearch index which a message will be sent to, at runtime?  For example, say we have a single topic with all items from a particular database table (populated by Debezium).  We want to be able to choose which index each individual message is sent to, based on some piece(s) of metadata in that message.

I believe we could have a separate stream processor (or maybe SMT) to take the items from the original topic and route them to individual topics, and then have each of those topics be sent to the relevant Elasticsearch index, but we'd like to avoid that for the following reasons:
1. This means duplicating all of the data in the original topic onto another topic.
1. We need to create new Elasticsearch indexes based on some user actions, so we'd now also need to create Kafka topics programmatically at runtime too.
1. This could result in a lot of topics - I know there's no hard limit on the number of topics Kafka can handle, but I believe it's recommended not to have too many (e.g. not more than something like several thousand).

**Comment by purbon** [comment]
Hi, 
  as you said already, for now the common way to do that would be using a SMT, actually the RegexRouter -> https://docs.confluent.io/current/connect/transforms/regexrouter.html#regexrouter. 

From your original message it is not clear to me why using a router would be a bad option for you. Is your request to have the index name as metadata inside the message?

Looking to understand more your concerns.

**Comment by yonigibbs** [comment]
Thanks @purbon.  My understanding with that SMT is that it would result in lots of topics being created.  The documentation in the link you sent states:

> Update the record’s **topic** using the configured regular expression and replacement string.

We have one source topic (populated by Debezium from a single DB table, for example), from which we want to take all the records and put them into Elastic, but each record might go into a different **index** in Elasticsearch.  So if we use this SMT, won't that result in lots of topics being (redundantly) created in Kafka?

In answer to your question: yes, we'd like to make the decision on which index to send the document to, based on some field in the data in the message in the Kafka topic.

**Comment by carmour24** [comment]
Hi @purbon,

Further to Yoni's comment, the intended index is included as a field in the body of the message so, aside from the issue of a potentially high number of topics being created, I don't think the RegexRouter would be suitable as it only performs search and replace on the topic itself not the content. Am I correct in thinking that?

It looks as though we can achieve what we want, routing to one of a potentially large number of indexes without creating a topic for each, by specifying a pipeline to be executed when a document is inserted into elastic but I don't see any way to accomplish that with the connector at present. Or is there perhaps some way to accomplish that that I'm missing?

Adding a default pipeline is coming in the next release of elastic, so waiting for that may solve our problems depending on when it is released.

Thanks

**Comment by roadSurfer** [comment]
There is #72 about being able to specify a pipeline to use, but that doesn't have made it into the official codebase.

**Comment by levzem** [comment]
@yonigibbs 
the SMT will not result in creating redundant topics. The way an SMT works is that it intercepts a record coming from Kafka, applies the transformation, and then passes it to the connector. 

Please let me know if you have further concerns.

**Comment by yonigibbs** [comment]
Ah, great, so if I'm understanding you correctly, the SMT can make it _seem_ like a message came from topic X, when in fact it's in Kafka in topic Y?  And topic X doesn't even have to exist in Kafka?  If so, that's great, that's what we wanted when looking at this initially.  Thanks @levzem.

**Comment by levzem** [comment]
@yonigibbs that is correct
