### ISSUE TITLE
Topic addition and deletion

### ISSUE THREAD

**Issue by monkey3199** [confluentinc/kafka-connect-elasticsearch#25]
Hello, I've been using this connector. And I need to add or delete topics frequently.

Actually, I know one solution to update topic configuration.

That is to use Kafka connect REST API, 
"PUT /connectors/{name}/config - update the configuration parameters for a specific connector".

But it takes too much time because it updates total configuration and rebalances the partitions.

I need the faster solution to update topics exclusively without restarting connector.

Do you have any idea?

**Comment by shikhar** [comment]
Hi @monkey3199, this is more of a connect framework feature request. Would you mind opening a KAFKA JIRA for it (with Component: `KafkaConnect`)? BTW, this may be a relevant issue https://issues.apache.org/jira/browse/KAFKA-3073
