### ISSUE TITLE
Allow more than 2 concurrent HTTP requests to the same route (Apache connection pool)

### ISSUE THREAD

**Issue by albf** [confluentinc/kafka-connect-elasticsearch#256]
After using different versions of the connector, I've noticed a quite noticeable performance hit when compared to a JMeter test plan also populating ES (same number of threads) or a not optimized simple distributed python connector (no buffer or fault tolerance features).

Since the difference was very noticeable for my use case, some extra investigation and profiling showed no memory, cpu or disk bootlenecks from both ES and Connect.  Instead, I got a decent amount of time waste on the following function (more than 50% for some configurations):

org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get ()
org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking ()
org.apache.http.pool.PoolEntryFuture.await ()

Check the following links/code/doc:

[PoolingHttpClientConnectionManager Documentation](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html) - "Per default this implementation will create no more than than 2 concurrent connections per given route and no more 20 connections in total"

[/jest/src/main/java/io/searchbox/client/JestClientFactory.java](https://github.com/searchbox-io/Jest/blob/ccc53cba57a30c1882ad9619da5efba7e92b77a6/jest/src/main/java/io/searchbox/client/JestClientFactory.java) - Same version as used (2.4). Accepts values for maxTotalConnection and MaxPerRoute. (Minor: jest was updated a lot since 2.4, more than 240 commits).

[JestElasticsearchClient.java](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/a97e2b048253c706bea80aa79aebfaa30a1d0424/src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java) -> Where the jest connection is configured. Noticed that those values don't seem to be passed. "max.in.flight.requests" has a default of 5, that doesn't seem right, especially when load balancers or ES-client nodes are used.

Those values are not configurable (since they are ignored by now). With "max.in.flight.requests" = 3 I got exactly 33% of time waste on those particular functions. Very suspicious, 3*0.66 ~= 2 (0.66 would be the active time).

Trying to fix/validate that, I patched Jest to actually use 100 for both values (hardcoded, just as a test), replaced the jest jar from Connect and... done, my speed was increased. Depending on the feedback, I could send a patch changing that. Some options:

- Have a configuration for that. Default should be >= max.in.flight.requests.
- Just calculate the amount needed (max.in.fligh.requests per worker thread?)
- Use a larger hardcoded value.

As I see, this is a bug. I don't see any mention about this on the [documentation](https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/index.html) or other issues.

Cheers

**Comment by levzem** [comment]
@albf great catch, I agree this is a misconfiguration. I have issued a PR #361 to address this issue. 

Thank you for your contribution.

**Comment by levzem** [comment]
closing as #361 has been merged
