### ISSUE TITLE
Customized connector jar does not work

### ISSUE THREAD

**Issue by ningliums** [confluentinc/kafka-connect-elasticsearch#257]
I am implemented an customized connector for Microsoft Kusto. I tried to place the uber jar with dependencies to the plugin.path, but it doesn't seem to work, I got the following error.

java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches org.apache.kafka.connect

I had to extract all the class files to the path and delete the jar, then it works fine. Could someone help to understand why? Is it a known issue?

**Comment by cricket007** [comment]
Not sure how this is a specific issue with Elastic connector?
