### ISSUE TITLE
how can i create .jar file for using these connector in linux?

### ISSUE THREAD

**Issue by elitius** [confluentinc/kafka-connect-elasticsearch#260]
Hello there,
I want to know how can i use jdurani / kafka-connect-elasticsearch this repo to build elasticsearch-kafka-connector.

**Comment by cricket007** [comment]
You can use `mvn clean package` to build the project, and it makes a tarball / zip, I believe, not one JAR. 

Also see https://github.com/confluentinc/kafka-connect-elasticsearch/wiki/FAQ

**Comment by levzem** [comment]
Closing because the question was answered.

Feel free to reopen if there are further questions.
