### ISSUE TITLE
Update same index from multiple sinks (different sources)

### ISSUE THREAD

**Issue by jeffbeagley** [confluentinc/kafka-connect-elasticsearch#262]
I have multiple Kafka Connectors and Topics that all house different sources of data, yet all contain reference to the same primary key (lets call "id"). Can you update Elasticsearch using this same id?

For example, source 1 has the following schema

```
{
    "id": 123
    "some_value": "yo"
    "details": {}
}
```
Source 2 has the following

```
{
    "id": 123
    "reference": 1
},
{
    "id": 123
    "reference": 2  
}
```
Is there a way I can create my expected outcome within ES to mimic the following

```
{
    "id": 123
    "some_value": "yo"
    "details": [
        {
            "id": 123
            "reference": 1
        },
        {
            "id": 123
            "reference": 2
        }
    ]
}
```
I have tried using Kafka's transforms with hoistfield but have been unsuccessful, it just replaces the entire document each time

**Comment by jeffbeagley** [comment]
@plarsson thanks for making me aware of the PR!

**Comment by pavel-agarkov** [comment]
@plarsson , any chance you have a Docker image of `cp-kafka-connect` with the changes you've mentioned?

**Comment by plarsson** [comment]
Sorry not anymore, we have since switched to another connector based on landoop https://github.com/Landoop/stream-reactor since we had performance issues with this one.
Our patched version is on https://github.com/devcode-git/stream-reactor
