### ISSUE TITLE
consumer group not being deleted on deletion of a connector

### ISSUE THREAD

**Issue by conorfennell** [confluentinc/kafka-connect-elasticsearch#267]
Expected Behaviour:
The consumer group is deleted when the connector is deleted. Therefore when a connector is recreated with the same name after a deletion it will start at the earliest offset.

Actual Behaviour:
Steps:
1. Deploy Connector:
`http:/sink-connector:8083/connectors`
```
{
	"name": "conor",
	"config": {
		"name": "conor",
		"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
		"topics": "conor",
		"connection.url": "http://es-live-elasticsearch-client.hekate:9200",
		"connect.elastic.url": "elasticsearch-search-cluster.default.svc.cluster.local:9200",
		"type.name": "_doc",
 		"schema.ignore": "true",
 		"behavior.on.null.values": "delete",
 		"key.converter": "org.apache.kafka.connect.storage.StringConverter",
 		"key.converter.schemas.enable":"false",
		"value.converter": "org.apache.kafka.connect.json.JsonConverter",
		"value.converter.schemas.enable": "false",
		"topic.index.map": "conor:conor",
		"batch.size": "250",
		"max.buffered.records": "1500",
		"flush.timeout.ms": "10000"
	}
}
```
2. Delete Connector
`http:/sink-connector:8083/connectors/conor`
```
{
	"name": "conor",
	"config":{
		"name": "conor",
		"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector"
	}
}
```

3. Check consumer group

The consumer group is given the same name as the connector name and still exists after step 2.

4. Deploy the connector again with the same configuration.
The connector uses the same consumer group which was not deleted and therefore does not start consuming at the earliest point of the topic.

**Comment by cricket007** [comment]
I believe this is being tracked in Apache Kafka JIRA, since it is a general Connect framework issue, not with Elastic connector itself. 

If you need to reset a consumer group, you will need to delete the connector, then issue a `kafka-consumer-groups --reset-offsets` command

**Comment by vikramsinghchandel** [comment]
@conorfennell were you able to find any solution to your problem?
