### ISSUE TITLE
JestClient HTTP timeouts

### ISSUE THREAD

**Issue by shikhar** [confluentinc/kafka-connect-elasticsearch#27]
We aren't currently setting connection and read timeouts on the HTTP client. I believe the default is infinite.

**Comment by shikhar** [comment]
The default is actually 3s.

**Comment by joseluisillana** [comment]
If you increase the value of the read timeout in code, in ElasticsearchSinkTask, you can test if it works.
[...]
String address = config.getString(ElasticsearchSinkConnectorConfig.CONNECTION_URL_CONFIG);
        JestClientFactory factory = new JestClientFactory();
        factory.setHttpClientConfig(new HttpClientConfig.Builder(address).readTimeout(60000).multiThreaded(true).build());
        this.client = factory.getObject();
[...]

**Comment by levzem** [comment]
@shikhar the connection and read timeouts are now being set properly

https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java#L160-L176

closing this as a result
