### ISSUE TITLE
Default value in avro schema

### ISSUE THREAD

**Issue by Reeebuuk** [confluentinc/kafka-connect-elasticsearch#271]
One of the fields in our avdls contain default value

.avdl 
  `record UserName {
    string userName = "no name";
  }`

In a message
   `union {null, UserName} userName;`

During the startup of the job we get

Cannot create mapping ....
`"userName":{"properties":{"userName":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}},"null_value":"no` name"}}} ...`

 `{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [userName] has unsupported parameters:  [null_value : no name]"}],"type":"mapper_parsing_exception","reason":"Mapping definition for [userName] has unsupported parameters:  [null_value : no name]"}`

Which would mean that currently ES-connect doesn't support default values in a schema? Is there a workaround?

**Comment by sujiea** [comment]
The problem is comming from Elatic Search dataType 'text' does not have null_value parameters. ES-connect need to exclude the text type for null_value generation when doing the mapping. I have submitted a ticket for confluent.

**Comment by sujiea** [comment]
Elastic Search Ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/text.html#text-params

**Comment by purbon** [comment]
fixed by the merge of #302
