### ISSUE TITLE
Records deleted from mysql aren`t being deleting in ES

### ISSUE THREAD

**Issue by altmax79** [confluentinc/kafka-connect-elasticsearch#273]
I have setup streaming from Mysql source to ES sink (version: confluent 5.1.0, ES 6.5.4, Mysql 5.7).
INSERT and UPDATE works perfectly, but DELETE is not being executed in ES.
Here mysql source connector: 
{
      "name": "mysql-connector",
      "config": {
            "connector.class": "io.debezium.connector.mysql.MySqlConnector",
            "database.hostname": "localhost",
            "database.port": "3306",
            "database.user": "debezium",
            "database.password": "*******",
            "database.server.id": "42",
            "database.server.name": "demo",
	    "database.whitelist": "demo",
	    "include.schema.changes": "true",
            "database.history.kafka.bootstrap.servers": "localhost:9092",
            "database.history.kafka.topic": "dbhistory.demo",
	    "transforms": "route",
	    "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
	    "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
	    "transforms.route.replacement": "$3"			
       }
    }

And ES sink connector:
{
  "name": "elastic-sink",
  "config": {
    "topics": "customers_4",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "key.ignore": "false",
    "schema.ignore": "false",
	"transforms": "unwrap,InsertKey,extractKey",
	"transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope", 
	"transforms.unwrap.drop.tombstones": "false", 
	"transforms.unwrap.drop.deletes": "false",
	"transforms.InsertKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
	"transforms.InsertKey.fields":"ID",
	"transforms.extractKey.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
	"transforms.extractKey.field":"ID",	
    "type.name": "type.name=kafkaconnect",
	"behavior.on.null.values": "delete",
    "connection.url": "http://localhost:48075"
  }
}

**Comment by cabaumgartner** [comment]
Did you ever solve this problem? I am having a similar problem. I can't get the ES connector to delete a document. Thanks.

**Comment by altmax79** [comment]
Yes i solve this problem the sink connector was wrong. If you insert property behavior.on.null.values, it works if a key is populated with the the _id of record in ES to delete and body is null. So in my case the key converter doesn't work .
I attach below two examples that works for me:
----------------Body serialized in AVRO
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/ \
     -d  '{  
   "name":"elastic-sink-2",
   "config":{  
      "connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
      "topics":"users_repart,user_attributes_value_repart",
      "topic.index.map":"users_repart:users,user_attributes_value_repart:users_attributes",
      "batch.size": 4000,
      "connection.url":"http://192.168.99.101:9200",
      "type.name":"type.name=kafkaconnect",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "key.converter.schemas.enable": "false",
      "value.converter": "io.confluent.connect.avro.AvroConverter",
      "value.converter.schema.registry.url": "http://localhost:8081",
      "behavior.on.null.values":"delete"
   }
}'


-------------------------------------------------Bosy serialized in JSON
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/ \
     -d  '{  
   "name":"elastic-sink",
   "config":{  
      "connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
      "topics":"users_enriched_json",
      "tasks.max": 5,
      "batch.size": 4000,
      "connection.url":"http://192.168.99.101:9200",
      "type.name":"type.name=kafkaconnect",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "key.converter.schemas.enable": "false",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "value.converter.schemas.enable": "false",
      "schema.ignore": "true",
      "behavior.on.null.values":"delete"
   }
}'
