### ISSUE TITLE
Support https proxy

### ISSUE THREAD

**Issue by sslavian812** [confluentinc/kafka-connect-elasticsearch#276]
Is there https proxy supported?
Consider the following config:
  ```
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "tasks.max": "1",
    "topics": "test-elasticsearch-sink",
    "key.ignore": "true",
    "connection.url": "http://my-elastic:80",
    "type.name": "event",
    "name": "elasticsearch-sink",
    "elasticsearch.index.prefix" : "kafka",
    }
```
How can I make the connector "talk" to elastic through a proxy `https://my-proxy:443`?

**Comment by shnplr** [comment]
A similar change was recently merged - [https://github.com/confluentinc/schema-registry/commit/4a106a1b9bd417edbecddfb65a474a1701b6d5b3](https://github.com/confluentinc/schema-registry/commit/4a106a1b9bd417edbecddfb65a474a1701b6d5b3)

**Comment by levzem** [comment]
@sslavian812 this is a good feature request. We will continue on #277

**Comment by levzem** [comment]
closing because #373 has merged. Thanks @sslavian812!
