### ISSUE TITLE
kafka connect is down when Elasticsearch is down !

### ISSUE THREAD

**Issue by beks2016** [confluentinc/kafka-connect-elasticsearch#279]
Hey everbody
Beside max.retries parameter , is theire any mechanim to keep messages in kafka brokers when Elasticseach  is down so it can be pushed again to ES when it's up ? or how can we keep track of lost messages in this case ?
best regard :)

**Comment by cricket007** [comment]
Not sure I undestand... Connect doesn't remove messages from Kafka, they are there for as long as the topic's retention is set to.

**Comment by beks2016** [comment]
thanks for your response . but when ES is down the worker will be stopped no ?

**Comment by cricket007** [comment]
The tasks for that connector will be, but it will not halt the entire Connect process for other connector tasks, no

**Comment by levzem** [comment]
closing because answered
