### ISSUE TITLE
Using the timestamp field within record for ES index

### ISSUE THREAD

**Issue by mike-treadway** [confluentinc/kafka-connect-elasticsearch#282]
Hi, I have records that contain a field with a timestamp that I'd like to use instead of the kafka record timestamp, which is when the record was ingested. I'm currently using the `org.apache.kafka.connect.transforms.TimestampRouter`, and _think_ I may have a series of SMT to to this, but wanted to make sure I was on the right track and there's not a simpler way.

TimestampConverter (put the TS field in the correct format)
ExtractTopic (update the topic name to include the newly formatted timestamp)

My issue with the above, is that I want the original timestamp field within the record to remain when persisted to ES. 

What I really need is for the TimestampRouter to allow me to specify a field within the record.

**Comment by t-d-d** [comment]
See ExtractTimestamp transform.  https://github.com/jcustenborder/kafka-connect-transform-common#extracttimestampvalue

Available on Confluent Hub https://www.confluent.io/connector/kafka-connect-common-transformations/

This sets the message timestamp from a named field (so it can then be processed by the TimestampRouter.)

(We actually wrote our own version based off this with some more configuration options.)

**Comment by levzem** [comment]
closing because answered
