### ISSUE TITLE
Obtain timestamp from Kafka Message - Transform to Date

### ISSUE THREAD

**Issue by martin-kieliszek** [confluentinc/kafka-connect-elasticsearch#283]
**Goal:**
Use `kafka-connect-elasticsearch` to:
1. grab the available kafka message `timestamp` field 
2. transform it to a date
3. take the transformed value and insert it into the target elasticsearch index as a `date` type 

ie. transform from long to date

**What have I done already?**
I have succesfully set up a `kafka-connect-elasticsearch` properties file that grabs the "default" `timestamp` field that a Kafka message produces

This "default" `timestamp` field is the value that a broker will append to a message when the following configuration is set on a Kafka Broker:

`KAFKA_MESSAGE_TIMESTAMP_TYPE=LogAppendTime`

**What is the problem then?**
However, the time that is inserted into elasticsearch is:
1. a long (3 digits longer than unix epoch) 
2. not a date, time, timestamp (exceptions are thrown when attempting to `transform.target` these properties - however when set to `unix`, the transform proceeds as shown below)
3. ultimately, the inserted long is recognised in elasticsearch/kibana only as a long and has no reference to date capabilities

An example of the kafka timestamp long that is produced in elasticsearch after the below properties file transforms are excecuted is:
```
1552810119468
1552816663511
1552818236358
```
The actual values that I desire the transform to output would be
```
1552810119
1552816663
1552818236
```

See https://www.unixtimestamp.com/index.php for the reference I have used
eg. 
**Current value conversions:** `1552810119468` = `08/05/51176 @ 8:17am (UTC)` **INCORRECT!**
however if you remove the last three digits
**Desired transform conversion X/1000** `1552810119` = `03/17/2019 @ 8:08am (UTC)`
 **CORRECT!**
**What is your transform configuration?**
```
transforms=InsertMessageTime,ConvertTimeValue
transforms.InsertMessageTime.type=org.apache.kafka.connect.transforms.InsertField$Value
transforms.InsertMessageTime.timestamp.field=timestamp
transforms.ConvertTimeValue.type=org.apache.kafka.connect.transforms.TimestampConverter$Value
transforms.ConvertTimeValue.target.type=unix
transforms.ConvertTimeValue.field=timestamp
transforms.ConvertTimeValue.format=yyyy-MM-dd HH:mm:ss
```

Note the above `transforms.ConvertTimeValue.format` does nothing when it reaches the elasticsearch index. The value is still a long. It would be great if someone can clarify if I can transform the long value by dividing it by 1000 and confirm whether that would succesfully enable the unix format to work?

**So to remind us again, what is it exactly you want in one sentence?**
I want to be able to rip out the default timestamp `long` value that is available within a Kafka Message, and have that value converted to a `timestamp/date` type prior to insertion into an elasticsearch index

Please reach out if you have any questions on my setup - I hope I have made it clear

**Comment by lhedjazi** [comment]
Hi martin-kieliszek,
I am facing the same issue. Have you find a workaround?
Thanks

**Comment by rince86** [comment]
Hi Guys,

I have also stumbled upon this problem and seems that it it not possible to map timestamp "long" type into "date" in Kafka Connect.
However - as a workaround - this mapping can be created in Elasticsearch as described here:

[https://github.com/grafana/grafana/issues/4321#issuecomment-282467390](url)

Also there is no problem with long format itself - 3 digits longer than unix epoch means that it is millisecond linux epoch and Kibana/Grafana are natively able to recognize it and convert it to long date format ex:
2019-07-03T12:54:15.136Z

**Comment by lhedjazi** [comment]
Thanks rince86 for the insights.
Yes I endedup also by tranforming it in Elasticsearch using templates. Now it works fine.

Lyamine

**Comment by levzem** [comment]
closing because workaround is available

**Comment by fml2** [comment]
Isnt't it so that you should use `target.type=string` to transform a long to a date string? Then the format is respected. The transformation is done like this: first, the value is transformed to a date (log -> Date), then the date is trasformed to the target type (formatted string).

**Comment by AdrianaTheo** [comment]
You should use:::
Kafka_Datetime =  time.strftime('%m/%d/%Y %H:%M:%S',  time.gmtime(ts/1000.))

**Comment by JonathanNgoni** [comment]
hie @AdrianaTheo   may you please explain your solution , i'm having the same problem and i really want a solution. Thank you in advance

**Comment by AdrianaTheo** [comment]
Hi, @JonathanNgoni I am working with confluent_kafka library.
In this library when you want to get the timestamp of the incoming message you need to call the function **msg.timestamp()** now, in order to convert it in a date-time format, you need the function **time.strftime()**.  So, the final Kafka date-time could be:
kafka_datetime = time.strftime('%m/%d/%Y %H:%M:%S',  time.gmtime(msg.timestamp()[1]/1000.))

**Comment by Tashweena** [comment]
@martin-kieliszek 
Could you please tell me how you  set up a kafka-connect-elasticsearch properties file that grabs the "default" timestamp field that a Kafka message produces ?

What configurations did you use? I have tried a bunch of different transforms but nothing is working for me. 
(A little bit of context: currently I can see the property CreatedTime but I want to append that field to my message when sending them to Elasticsearch)
