### ISSUE TITLE
Kafka connect messages not getting consumed and no errors reported

### ISSUE THREAD

**Issue by hisijo** [confluentinc/kafka-connect-elasticsearch#297]
Using Kafka connect to load data to elastic search. Sink task is getting started successfully, but no messages are getting delivered. 
config is below
sink.properties
name=pos-ptp-elastic-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
client.id=tops-elastic-connect
topics=ptpservice
topics.index.map=transactions:transaction
key.ignore=false
connection.url=http://localhost:32771
type.name=transaction
schema.ignore=true
key.converter=org.apache.kafka.connect.json.JsonConverter
#key.converter=org.apache.kafka.connect.storage.StringConverter 
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.flush.interval.ms=10000
flush.start=3

transforms=createKey,extractInt
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=legacyId
transforms.extractInt.type=org.apache.kafka.connect.transforms.ExtractField$Key
transforms.extractInt.field=legacyId

standalone.properties
bootstrap.servers=kafka.internal:9093
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.file.filename=/tmp/connect.offsets
# Flush much faster than normal, which is useful for testing/debugging
offset.flush.interval.ms=10000
flush.start=3
plugin.path=./connect/connect-es,./connect/kafka
security.protocol=SSL
security.inter.broker.protocol=SSL
ssl.truststore.location={{truststore_location}}
ssl.truststore.password=%% JKS_PASSWORD %%
ssl.keystore.location={{keystore_location}}
ssl.keystore.password=%% JKS_PASSWORD %%
ssl.key.password=%% JKS_PASSWORD %%

Last log line is below
[2019-04-04 07:20:16,344] INFO Setting server pool to a list of 1 servers: [http://localhost:32771] (io.searchbox.client.AbstractJestClient:56)
[2019-04-04 07:20:16,345] INFO Using multi thread/connection supporting pooling connection manager (io.searchbox.client.JestClientFactory:223)
[2019-04-04 07:20:16,420] INFO Using default GSON instance (io.searchbox.client.JestClientFactory:69)
[2019-04-04 07:20:16,420] INFO Node Discovery disabled... (io.searchbox.client.JestClientFactory:86)
[2019-04-04 07:20:16,421] INFO Idle connection reaping disabled... (io.searchbox.client.JestClientFactory:98)
[2019-04-04 07:20:16,479] INFO JsonConverterConfig values:
	converter.type = value
	schemas.cache.size = 1000
	schemas.enable = false
 (org.apache.kafka.connect.json.JsonConverterConfig:279)
[2019-04-04 07:20:16,481] INFO WorkerSinkTask{id=pos-ptp-elastic-sink-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:303)

Tried to troubleshoot using similar issues on hdfc connector and didn;t help. https://github.com/confluentinc/kafka-connect-hdfs/issues/162 

Anyone has clue into this?

**Comment by hisijo** [comment]
Some additional info on this. This sink was working when the kafka topic was using plain_text for security protocol. With conversion to SSL, it stopped working. I can consume to a console with SSL without issues.

**Comment by cyrusv** [comment]
@hisijo, the connector will only connect using SSL if you configure the `connection.url` property to use protocol `https://`. Please try this, and let me know if it resolves the issue

**Comment by jabilivakkalanka** [comment]
Is this issue resolved? I am facing some similar with jdbc connector.

**Comment by tliebhart** [comment]
Is this issue resolved? I am facing some similar with jdbc connector.

**Comment by jabilivakkalanka** [comment]
Yes. we added the following parameters.
consumer.sasl.mechanism=PLAIN
consumer.security.protocol=SASL_SSL
consumer.sasl.jaas.config=

**Comment by cyrusv** [comment]
Due to some confusion, we've added a config param to let users explicitly state their desired protocol, available in 5.3.0 https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/configuration_options.html#security

I hope this clears up the issue -- I am closing for now please tag me if issue persists
