### ISSUE TITLE
Way to customize Kafka+ES connector to put multiple topics in a same topic

### ISSUE THREAD

**Issue by priyaselladurai** [confluentinc/kafka-connect-elasticsearch#298]
I'm new ES and Kafka. To speed up the searching process for our application, We thought to use Elastic Search. For this, we have enabled CDC in MsSQL (maintains all transactions of an application). 
Through Kafka and Debizium Connect /Elastic Connector, we are trying to solve this. 
i.e, MsSQL(CDC) => Kafka =>ElasticSearch
CDC to push the data changes immediately to Kafka.

The problem is.
How we can put the relational tables data into ES in a single index and single topic (denormalized data)?
Is there any way to do index data from multiple topic of Kafka into same type of index in ES?

**Comment by patsadow2** [comment]
Could you provide your dock yaml with connector config ?

**Comment by gulecroc** [comment]
You have to use [Kafka Connect Transformations](https://docs.confluent.io/current/connect/transforms/index.html) with [RegexRouter](https://docs.confluent.io/current/connect/transforms/regexrouter.html#regexrouter) :

```
name=myConnectorName
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
type.name=kafka-connect
tasks.max=1
connection.url=http://localhost:9200
topics.regex=^.*$
transforms=myTransformation
transforms.myTransformation.type=org.apache.kafka.connect.transforms.RegexRouter
transforms.myTransformation.regex=^.*$
transforms.myTransformation.replacement=newTopicNameUsedForElasticIndex
```

**Comment by levzem** [comment]
@gulecroc gave the correct answer, thank you! 

@priyaselladurai I am going to close this but, if you have any further questions feel free to reopen anytime!

**Comment by nchauhan5** [comment]
@gulecroc @levzem @iXmonvi33 @astubbs  This issue should be reopened I guess? given the fact that The connector does not currently support Single Message Transformations (SMTs) that modify the topic name as per - The connector does not currently support Single Message Transformations (SMTs) that modify the topic name

**Comment by astubbs** [comment]
@nchauhan5 not sure why I'm being tagged?
