### ISSUE TITLE
ES 7 dropped the usage of mapping.types, therefore the property `type.name` should be dropped as well 

### ISSUE THREAD

**Issue by creativelikeadog** [confluentinc/kafka-connect-elasticsearch#300]
The new version `7.0.0` removed the `mapping types`  the property `type.name` should not be used anymore.

see: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

**Comment by webmanAv** [comment]
why did you close it? it is breaking change

**Comment by HBO2** [comment]
I have the same issue. Can anybody help me how to deal with ES 7
