### ISSUE TITLE
Send complex Key in Kafka Topic message to elastic search

### ISSUE THREAD

**Issue by NitikaGoel** [confluentinc/kafka-connect-elasticsearch#303]
I have messages in my Kafka Topic, where key is of struct type. No single field in the key is having unique value. So I want to use entire key(STRUCT type) to form document Id because otherwise document Id can not  be created uniquely. I know we can extract key to form document Id, but extract key transform does not take list of fields from key struct, it only takes a single field as string.

Is there a way to fetch all the fields from key and then form a document Id.

OR

Is there a way to extract all the fields from key and insert them to value of the message record. Like Kafka transform for keytovalue. I know we have Kafka transform for ValuetoKey but I want the other way round.

**Comment by cricket007** [comment]
There is an SMT for this 

https://github.com/jcustenborder/kafka-connect-transform-archive/

**Comment by NitikaGoel** [comment]
Thanks, its kind of helpful.
For the time being I ,modified kafka-connect-elastissearch for this class DataConverter.java to allow key to be inserted as part of value payload. This did solve my purpose for the time being but was not a long term solution.
Having an exclusive transormations will help a lot with future work.

**Comment by levzem** [comment]
as of now the connector will be supporting this. A custom SMT can get this functionality done. Closing for that reason.
