### ISSUE TITLE
Type of the write operation to ElasticSearch (INDEX/UPDATE) is not present in the configuration

### ISSUE THREAD

**Issue by alexmorosmarco** [confluentinc/kafka-connect-elasticsearch#307]
I have 2 questions regarding the type of the write operation to ElasticSearch (INDEX/UPDATE), as I do not see it documented in [the Configuration of the connector](https://docs.confluent.io/5.2.1/connect/kafka-connect-elasticsearch/configuration_options.html).

1. **What is the default ElasticSearch operation that the connector executes?**
Index or update?

2. **How can I choose the ElasticSearch operation to be an index or an update operation?**
In some cases I want to completelly override the document present in ElasticSearch, so I want an index operation.  
In others I want just to add the information received from Kafka, so I want an update operation.

**Comment by levzem** [comment]
@alexmorosmarco, the connector has two write methods: `INSERT` and `UPSERT`. `INSERT` is the default value for the connector.

`INSERT` corresponds to `INDEX` - it inserts a nonexistent document or completely replaces an existing one
`UPSERT` corresponds to `UPDATE` - it either inserts a nonexistent document or update the existing doc by only replacing/adding provided fields.

this configuration is set by `write.method`.

The connector only supports one of these methods at a time. If you want both of these functionalities you will have to have two different connectors running each with one of the write methods reading from index and update topics respectively. 

As of now, there is no way to selectively tell the connector to `INSERT` some records and `UPSERT` others. 

Hope this answers your questions

**Comment by levzem** [comment]
Closing this to no response - feel free to reopen if you have any further questions

**Comment by klesgidis** [comment]
Hey guys, this is still not documented. Is there any reason for that?
