### ISSUE TITLE
ElasticsearchSinkConnector for real-time data streams

### ISSUE THREAD

**Issue by unavconota** [confluentinc/kafka-connect-elasticsearch#315]
I’m new to ELK and Kafka. 

I have set up Kafka (landoop fast dev) to ingest real-time GNSS data streams. I can inspect the data via the Kafka Topic UI so I know it is making it into Kafka.
I can also see the incoming messages using 
kafka-console-consumer --bootstrap-server localhost:9092 --topic all_rtx -max-messages 100

I am now trying to set up the connector to Elastic Search. I am using  the Kafka Connect UI

connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
type.name=kafkaConnectAllRTX
topics=all_rtx
tasks.max=1
value.converter.schemas.enable=false
connection.url=localhost:9200
key.ignore=true
value.converter=org.apache.kafka.connect.json.JsonConverter
schema.ignore=true

Initially I can see the data arrive in Elastic Search. I use the Kibana interface to see that and I can plot the streams with Grafana. But, after about two hours data stops showing up in Elastic Search, even though data are still going into Kafka.
No errors are appearing on the Connector UI either, it shows "Kafka elastic search is RUNNING” and it is in a green state.

Does anyone have any suggestions of where to look for problems? I am running everything from docker containers.  

Thanks
Kathleen

**Comment by babadofar** [comment]
You need to look at the logs from elasticsearch and kafka connect, they will usually tell you what is wrong. Most likely what you see is that elasticsearch refuses to accept new data. This is could be due to a full disk, a swamped thread pool, mapping errors etc.

**Comment by levzem** [comment]
@unavconota were you able to resolve this issue?

**Comment by levzem** [comment]
Closing due to no response. Please feel free to reopen if you are still having issues.
