### ISSUE TITLE
Push message to specific elastic index based on values of one or more fields of the message

### ISSUE THREAD

**Issue by rohankapoor1** [confluentinc/kafka-connect-elasticsearch#319]
There is an use case where I want messages to be pushed to specific elastic index based on the values of one or more fields of the given message. I checked the configurations and various open bugs and couldn't find any proper solution. For eg:

{"fieldA" : "valueA",
"fieldB" : "valueB",
"fieldC" : "valueC",
"fieldD" : "valueD"
}

I expect that this message should go to index: "valueA-valueB:valueD"
Can we achieve this with existing Sink connector ?

**Comment by eneveu** [comment]
**I think you should do this using a custom Kafka-Connect SMT (Single Message Transform) that updates the topic depending on the key/value.**

You probably want to take inspiration from the open-source [RegexRouter](https://docs.confluent.io/current/connect/transforms/regexrouter.html) and [TimestampRouter](https://docs.confluent.io/current/connect/transforms/timestamprouter.html) to create your own transformation that does exactly what you want. You'll need to package it as a Kafka Connect plugin to deploy it.

Confluent has a proprietary [ExtractTopic transformation](https://docs.confluent.io/current/connect/transforms/extracttopic.html), but I don't think it does enough for you, so you'll probably need to write your own.

#### Why do I think this is the best practice ?

1) kafka-connect-elasticsearch [has a `topic.index.map` option to map topics to different indexes](https://docs.confluent.io/5.2.1/connect/kafka-connect-elasticsearch/configuration_options.html#data-conversion), but it is deprecated, and they suggest using an SMT to update the topic:

> `topic.index.map`
> This option is now deprecated. A future version may remove it completely. **Please use single message transforms, such as RegexRouter, to map topic names to index names.**
> 
> A map from Apache Kafka® topic name to the destination Elasticsearch index, represented as a list of topic:index pairs.

2) The [TimestampRouter documentation](https://docs.confluent.io/current/connect/transforms/timestamprouter.html) seems to point to this best practice:

> Update the record's topic field as a function of the original topic value and the record timestamp.
> 
> **This is useful for sink connectors, because the topic field often determines the equivalent entity name in the destination system (for example, a database table or search index name).**

**Comment by rohankapoor1** [comment]
Hi @eneveu ,
I was thinking to propose a new configuration option (like record.index.map) while setting up the connector where user can give a record field or combination of record fields which can be used to push this record.
Eg:
Record = {"fieldA" : "valueA",
                 "fieldB" : "valueB",
                 "fieldC" : "valueC",
                 "fieldD" : "valueD"}

record.index.map = <fieldA>-<fieldC>

So, this record will be stored into ES index named: **valueA-valueC**
As it will be a default configuration provided so any external Kafka connect plugin like  RegexRouter and TimestampRouter may not be needed. And I am thinking this will be useful for many consumers.

**Comment by levzem** [comment]
@rohankapoor1, as @eneveu mentioned, the proper solution will be to use an SMT. We will not be implementing this feature within in the connector because we do see much sense in reimplementing existing functionality provided by SMTs (which also can be applied to any connector) within a single connector. 

I will close the issue, but feel free to reopen if you have further comments to add.
