### ISSUE TITLE
Create mapping exception

### ISSUE THREAD

**Issue by srijiths** [confluentinc/kafka-connect-elasticsearch#32]
```
[2016-10-07 08:59:13,507] ERROR Task elastic-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:401)
org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"sample":{"type":"string"}} -- {"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : string]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : string]"}
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:64)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:200)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:119)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:381)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I am using ES version 2.3.4 and kafka 0.10.0.1. So i downgraded the version of elasticsearch,lucene and kafka according to my platform and build JAR.  Below are my connector properties

```
type.name=sample
topics=sensor-in
key.ignore=true
value.ignore=true
connection.url=http://A.B.C.D:9200/
```
I tested two cases 

- Index and Type is already exists in ES cluster
- Connector will create Index and Type with mapping

But both cases i am getting above exception.
Thank You

**Comment by shikhar** [comment]
@srijiths there is no config called `value.ignore`, maybe you meant to try `schema.ignore`?

**Comment by shikhar** [comment]
@srijiths what's the schema of the data in the source topic? Seems like it is primitive strings. I see that we create an incorrect mapping (no 'properties' element specifying the fields) in this case. Even with `schema.ignore=true`, the indexing request will not be of the `{field: 'value'}` form ES expects.

So I think you will need to do some pre-processing on the stream before using the ES sink connector.

In future, it may be possible to utilize a 'Single Message Transform' feature we are thinking about for Kafka Connect to hoist primitive values into e.g. a Struct schema with some field name.

**Comment by srijiths** [comment]
@shikhar Thanks for the replay. I was not using any schema in the source topic. It was just a JSON. Does it means that ES Sink / HDFS Sink always expects messages in Avro format with schema enabled ?

**Comment by shikhar** [comment]
@srijiths This connector does support schemaless data, so if you configure the `JsonConverter`for it and use `schema.ignore=true` in theory everything should work.

But if the connector actually saw your data as schemales, you wouldn't be getting to this point, since you'd run into this error here: https://github.com/confluentinc/kafka-connect-elasticsearch/blob/050cd6cee401a8f8025996782b1c5deb4e29ab7a/src/main/java/io/confluent/connect/elasticsearch/Mapping.java#L91-L93

Although you said you have JSON data in the topic, I suspect there is a corresponding STRING Avro schema registered with Schema Registry and you are using `AvroConverter` here. Is that right?

Using `JsonConverter` and `schema.ignore=true` should hopefully get things working for you.

**Comment by srijiths** [comment]
@shikhar Thank you , i missed schema.ignore=true. I will try with this and let you know the results.

**Comment by srijiths** [comment]
@shikhar Yes , its working with `JsonConverter `with `schema.ignore=true`.  But i have a doubt here. In kafka-connect-jdbs , when you say `JsonConverter `and if you have a JSON message. It seems like it will wrap the actual JSON message with in other JSON template with `schema `and `payload`

But when i use `JsonConverter `here i can only see my original JSON messgae in ES Index. 

Also when i try with `org.apache.kafka.connect.storage.StringConverter` with `key.converter.schemas.enable=fals`e , `value.converter.schemas.enable=false` with my JSON message , its not indexing . Getting an exception. Please find it below.

![01](https://cloud.githubusercontent.com/assets/1046319/19428166/07963860-9466-11e6-997d-0266a7492837.png)

Am i doing something wrong ? 

Thank You

**Comment by toabey** [comment]
i am trying to transform flat json records (Lat, Long) to a different schema {Location: {lat: , lon:}}.
I read about 'Single Message Transform', but still not able to do it using that . As it involves MetadataSchema then field definition using HoistField .  Is there any working example to using with elastic search sink ?
