### ISSUE TITLE
Make "behavior.on.malformed.documents" also cover "action_request_validation_exception"

### ISSUE THREAD

**Issue by milofelipe** [confluentinc/kafka-connect-elasticsearch#325]
Background: I have "key.ignore=false" and have old messages in my topic that don't have keys or have empty keys. Connector tasks fail because Elasticsearch is returning a validation error:

{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}

Would be great if there is an option to ignore errors like this so tasks don't stop running. Looking at the code, "behavior.on.malformed.documents" seems to be only concerned with "mapper_parsing_exception" and "illegal_argument_exception" errors. Requesting to add "action_request_validation_exception" to the list or implement a new configuration option for this.

**Comment by levzem** [comment]
@milofelipe this looks a relatively simple fix. Would you like to issue a PR?

**Comment by milofelipe** [comment]
> @milofelipe this looks a relatively simple fix. Would you like to issue a PR?

Yes.

**Comment by levzem** [comment]
closing because merged, thanks @milofelipe!
