### ISSUE TITLE
[Question] Initial heavy data load 

### ISSUE THREAD

**Issue by sor-barroso** [confluentinc/kafka-connect-elasticsearch#331]
Hello!

I recently started to play with Confluent Kafka as CDC from Postgres and Elasticsearch.

I'm using Debezium to fetch changes on DB and store on Kafka, after that, the Kafka Elasticsearch Connector starts to act sending data.

This approach works really fine on "live" mode but seems to be really slow on my initial load data (database snapshot), with Debezium producer set as "initial_only" snapshot mode.

The indexing rate in this process stuck at an average of **3000** records per minute, which seems to be a low number of records when compared with another process that I have that inserts on Elasticsearch via API bulk insert where I have more than **100K** records per minute being indexed. 

I understand that probably the connector does way more stuff during the index process but could I set it in a regardless manner to perform the initial load faster?

My connector config:
``` json
{
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "type.name": "kafka-connect",
    "flush.timeout.ms": "60000",
    "tasks.max": "20",
    "topics": "out_joined",
    "batch.size": "500",
    "name": "elastic-connector",
    "key.ignore": "false",
    "connection.url": "http://localhost:9200/",
    "max.in.flight.requests": "5",
    "max.buffered.records": "3000",
    "schema.ignore": "true"
}
```
Thanks

**Comment by lixueyu001** [comment]
有找到答案吗？我遇到了和你一样的问题。

**Comment by lixueyu001** [comment]
> 你好！
> 
> 我最近开始与Postgres和Elasticsearch的CDC一起与Confluent Kafka一起玩。
> 
> 我正在使用Debezium来获取数据库上的更改并将其存储在Kafka上，之后，Kafka Elasticsearch Connector开始执行发送数据的操作。
> 
> 这种方法在“实时”模式下确实可以正常工作，但是在将Debezium生产者设置为“ initial_only”快照模式的情况下，对于我的初始加载数据（数据库快照）来说似乎确实很慢。
> 
> 此过程中的索引速率平均每分钟停留**3000**条记录，与我通过API批量插入在Elasticsearch上插入的另一个过程（每分钟有10 **万**条记录）相比，这似乎是很少的记录被索引。
> 
> 我知道连接器在索引过程中可能会做更多的事情，但是我可以以任意方式设置它以更快地执行初始加载吗？
> 
> 我的连接器配置：
> 
> ```json
> {
>      “ connector.class ”：“ io.confluent.connect.elasticsearch.ElasticsearchSinkConnector ”，
>      “ type.name ”：“ kafka-connect ”，
>      “ flush.timeout.ms ”：“ 60000 ”，
>      “ task.max ”：“ 20 “ ”主题“：” out_joined “ ” batch.size “：“ 500 ”，
>      “ name ”：“弹性连接器”，
>      “ key.ignore ”：“ false ”，
>      “ connection.url ”：“ http：// localhost：9200 / ”，
>      “ max.in.flight.requests ”：“ 5 “，
>      ” max.buffered.records “：” 3000 “，
>      ” schema.ignore “：”真“ 
> }
> ```
> 
> 谢谢

有找到答案吗？我也遇到了同样的问题

**Comment by levzem** [comment]
@sor-barroso 

there are several configs that you can tune to make the connector faster.

`tasks.max`
`max.in.flight.requests`
'max.batch.size` - your max batch is only 500 which is pretty low if you want higher throughput you can increase this

there are other external factors that affect performance, so it is not always easy to determine the true cause. Your topic might not contain or might not be producing records fast enough or your internet connection might also be slow. There is also a known performance bug that got fixed and you might be affected by that, see #332

**Comment by sor-barroso** [comment]
Thank you @levzem, our Kafka solution is in stand by for now, so I won't be able to test it with a higher `max.batch.size` soon. Anyway, I hope it's gonna give a clue for those who are facing the same.

**Comment by levzem** [comment]
@sor-barroso another thing we have recently found in our connector is that you need to set `linger.ms` to a much higher value than the default of `1` as it affects performance significantly
