### ISSUE TITLE
[Feature] topic.index.map one topic - many indices

### ISSUE THREAD

**Issue by cgetzen** [confluentinc/kafka-connect-elasticsearch#333]
Example:
topic.index.map=topic1:index1,topic1:index2
I would like both index1 and index2 to contain the document.

**Comment by levzem** [comment]
@cgetzen as per #336, we can continue our discussion here

> 
we appreciate your contribution. Unfortunately, topic.index.map is a deprecated feature as mentioned in the documentation. We advise to use SMTs now to achieve the desired topic.index.map effect. It would send the wrong message by adding new functionality to a deprecated feature.

Doubly unfortunately, the only way I see to replicate this feature right now using SMTs is to have two instances of the connector running or having duplicate topics (i.e using replicator to copy a topic). I am open to any other suggestions on how we can provide this feature in a better way without having to result to either of those solutions.

**Comment by cgetzen** [comment]
Agreed with all of the above. My current project is stable with the modifications from #336 , and will probably not work on this further. However, if others run into the same issue and want to give it a shot: one option would be to store index metadata in kafka headers as opposed to topic names.
