### ISSUE TITLE
Elasticsearch connector fails when DLQ is enabled

### ISSUE THREAD

**Issue by arnitolog** [confluentinc/kafka-connect-elasticsearch#345]
I tried to enable DLQ functionality for my connector. The configuration is below:

```
 "name" : "es_sink",
 "config" : {
  "connector.class" : "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "tasks.max" : "2",
  "topics.regex" : "logging-(.+)",
  "connection.url" : "https://logging-cluster-es:9200",
  "connection.username": "logger",
  "connection.password": "xxxxxxxxxxx",
  "behavior.on.malformed.documents": "warn",
  "errors.deadletterqueue.topic.name": "deadletterqueue-logging",
  "errors.deadletterqueue.context.headers.enable": "true",
  "type.name" : "_doc",
  "key.ignore" : "true",
  "schema.ignore" : "true",
  "schemas.enable": "false",
  "key.converter.schemas.enable":"false",'
  "value.converter.schemas.enable":"false",
```
But once I enabled it, I got an error and connector couldn't start:
`
{"name":"es_sink","connector":{"state":"RUNNING","worker_id":"100.102.66.106:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"100.102.66.106:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Could not initialize dead letter queue with topic=deadletterqueue-logging at org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.createAndSetup(DeadLetterQueueReporter.java:89) at org.apache.kafka.connect.runtime.Worker.sinkTaskReporters(Worker.java:660) at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:524) at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:459) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1036) at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:117) at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1051) at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1047) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) at org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.createAndSetup(DeadLetterQueueReporter.java:80) ... 11 more Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment."}
`
without this option, the connector works as expected. So, I'm curious is it a bug, or I missed some config?

**Comment by arnitolog** [comment]
forgot to mention that I use Kafka and Kafka connect 2.3.0  and Elasticsearch connector 5.3.1

**Comment by clevandowski** [comment]
I get exactly the same error when I want to enable the dead letter queue.
Here is my configuration:

{
  "name": "topic_ES_Sink",
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "tasks.max": "1",
  "topics": "mytopic",
  "connection.url": "https://myESserver:9200",
  "connection.username": "kafka_user",
  "connection.password": "*********",
  "type.name": "kafka-connect",
  "retry.backoff.ms": 100,
  "max.retries": 50,
  "connection.timeout.ms": 1000,
  "read.timeout.ms": 3000,
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schemas.enable": false,
  "schema.ignore": true,
  "transforms": "insertField,regexRouter",
  "transforms.insertField.type": "org.apache.kafka.connect.transforms.InsertField$Value",
  "transforms.insertField.topic.field": "original-topic", 
  "transforms.regexRouter.type": "org.apache.kafka.connect.transforms.RegexRouter", 
  "transforms.regexRouter.regex": ".*",
  "transforms.regexRouter.replacement": "index-to-write",
  "errors.tolerance": "all",
  "errors.deadletterqueue.topic.name": "mytopic_DLQ",
  "errors.deadletterqueue.context.headers.enable": true
}

**Comment by arnitolog** [comment]
for some reason, DLQ topic is not created even when I specified 
connector.client.config.override.policy=All
in worker config and
"admin.override.errors.deadletterqueue.topic.name": "mytopic_DLQ",
"admin.override.errors.deadletterqueue.context.headers.enable": true
in the connector config

**Comment by levzem** [comment]
@arnitolog you are most likely missing admin client security properties that need to be configured on the worker level because DLQ has to create a topic

`admin.ssl.endpoint.identification.algorithm=https
admin.sasl.mechanism=PLAIN
admin.request.timeout.ms=20000
admin.retry.backoff.ms=500
admin.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
username="4Z3YGNJJNWCKR25W" password="xn2iUtQ9jbmqPhVz75i0LPcwafTDUKcYiiC3b88iRVCFdFpqor6cw4Ml18pDTEVo";
admin.security.protocol=SASL_SSL`

**Comment by levzem** [comment]
closing because answered but feel free to reopen if there are further questions
