### ISSUE TITLE
ES index date suffix

### ISSUE THREAD

**Issue by maxsakharov** [confluentinc/kafka-connect-elasticsearch#348]
It would be great if I can attach the date suffix to the end of the ES index. It is useful for time series data with retention policies where old indices should be periodically removed. 

I would add below configs to the task

```
index.suffix.date=true
index.suffix.date.format="-yyyy-dd-MM"
```

And the example of the ES index name would something like `index-name-2019-10-14`

Having `index.suffix.date` is not necessary at this point. Probably having an empty format would disable the date index suffix. It's just more explicit way of defining the property

I would like to know the community opinion on that. Happy to contribute!

**Comment by Duchadian** [comment]
The advised way of doing this is to use a [TimestampRouter transformation](https://docs.confluent.io/current/connect/transforms/timestamprouter.html#timestamprouter) on each of the records. You can already set this in the config of any Kafka Connect connector.

**Comment by maxsakharov** [comment]
Wow! I haven't seen that transformer. Thx for the advice @Duchadian
