### ISSUE TITLE
Infinite loop on retriable exception

### ISSUE THREAD

**Issue by nirajpatel** [confluentinc/kafka-connect-elasticsearch#35]
The following loop never terminates due to the middle condition always being `true`.

https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java#L344

**Comment by ewencp** [comment]
@nirajpatel The loop always decrements `remainingRetries` by 1 and will always throw an exception once the `remainingRetries` has dipped below 0. This is probably not as common a pattern as using a `while(true)` with a required `return`/`throw` in the loop, but is effectively the same pattern.

**Comment by nirajpatel** [comment]
@ewencp oh okay, but it seems like the `remainingRetries` is being ignored altogether and there will be infinite retries. Is that on purpose?

**Comment by shikhar** [comment]
@nirajpatel `remainingRetries` is not ignored, it is used here: https://github.com/confluentinc/kafka-connect-elasticsearch/blob/050cd6cee401a8f8025996782b1c5deb4e29ab7a/src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java#L355

**Comment by nirajpatel** [comment]
I think I was testing that last night and the same requests kept failing over and over again but I might be wrong. I have my own version now that doesn't ever stop the entire connector on exception though so I won't be able to test it. Looks good though @shikhar. Great job on this code! The refactor is great.
