### ISSUE TITLE
Problem with ElasticSearch connector

### ISSUE THREAD

**Issue by dabr-grapeup** [confluentinc/kafka-connect-elasticsearch#350]
Hello, I've problem that after upgrade to version 5.3.1 from 5.2.2. Our ElasticSearch connector isn't working anymore. Exception thrown isn't really helpful. Our ElasticSearch is in version: 7.1.1
```
java.lang.NullPointerException
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.getServerVersion(JestElasticsearchClient.java:231)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:142)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:133)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Any idea?

**Comment by ncliang** [comment]
The line that throw NPE is here - https://github.com/confluentinc/kafka-connect-elasticsearch/blob/v5.3.1/src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java#L231

Have you always been using 5.2.2 with ES v7? AFAIK, ES v7 support was not present in 5.2.2. Did you upgrade the ES version as well? From the NPE location, it looks like result does not contain the "nodes" JSON. It would help to peek at the result object to see if instead of the version response from ES, you are getting a 404 or something. Maybe you have firewall rules blocking version endpoint to ES7 deployment?

**Comment by dabr-grapeup** [comment]
Yes, this project is relatively young and initial connector version was 5.2.2 and ES v7, no upgrade on ES side. I'm able to connect to Elastic from container in which Kafka Connect is running, so it isn't a firewall. The most surprising thing is that it works with 5.2.2, which seems to has exactly same code to extract version from nodes...

**Comment by ncliang** [comment]
There were dependencies that got updated versions too.
```
nliang-MBP:~/dev/kafka-connect-elasticsearch (master)$ git diff v5.2.2...v5.3.1
...
-        <jest.version>2.4.0</jest.version>
+        <hamcrest.version>1.3</hamcrest.version>
+        <mockito.version>2.28.2</mockito.version>
+        <jest.version>6.3.1</jest.version>
```
My guess is that the behavior of Jest client changed when version endpoint could not be reached. Where before, there maybe was an empty `nodes` wrapper in the response causing you to go into [this](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/v5.3.1/src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java#L232) block of code and get default ES version 6, now it does not contain the empty `nodes` wrapper and thus causes NPE. You could verify by looking at server logs or peeking at the request with wireshark or something to see if version endpoint is actually hit and responded with 200 and some version JSON.

**Comment by dabr-grapeup** [comment]
I'm not able to check the actual request, because of all layers of the security. But when I send request from container, the response I got from 7.1.1 looks like this:
`HTTP/1.1 200 OK`
```
{
  "_nodes": {
    "total": 12,
    "successful": 12,
    "failed": 0
  },
  "cluster_name": "XYZ",
  "nodes": {
    "zAw1QQAxQhOZwI6ZTqfU5w": {
      "name": "XYZ",
      "transport_address": "XYZ:9300",
      "host": "XYZ",
      "ip": "XYZ",
      "version": "7.1.1",
... other stuff
```

**Comment by ncliang** [comment]
That looks like a valid response. If the client got that response, it should not NPE. What endpoint did you hit to get the response? The client should be trying to hit something like `/_nodes/_all/version`. 

Also, what do you have in your connector properties? One thing that I see changed from v5.2.2 to v5.3.1 is the addition of `elastic.security.protocol` config defaulting to `PLAINTEXT`, which would cause configs prefixed by `elastic.https.` to be ignored. Maybe you need to set this to `SSL`?

**Comment by dabr-grapeup** [comment]
Thanks! `elastic.security.protocol=SSL` did the trick. :)
