### ISSUE TITLE
The ElasticSearch Connector doesn't send data to the ElasticSearch ?

### ISSUE THREAD

**Issue by emy-lee** [confluentinc/kafka-connect-elasticsearch#351]
Hi everyone,
I have enabled this connector. But the problem is that when I send data with this command:
```
bin/kafka-avro-console-producer --broker-list localhost:9092 --topic my-test --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
```

Then there isn't any data in ElasticSearch:
```
health status index       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   my-test -RTNVKxESIa0SUoxm1sNXw   1   1          0            0       283b           283b
```

But the data is sent to the topic. Infact I can see it with this command:
```
$ bin/kafka-avro-console-consumer --bootstrap-server localhost:9092 --topic my-test --from-beginning
```

In the log of Connect, I get this:
```
[2019-10-31 21:32:41,835] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler

Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic my-test to Avro: 
...
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 201
Caused by: java.net.SocketTimeoutException: connect timed out
```

So, why is there no data in ElasticSearch?
Any idea?

**Comment by jmwilli25** [comment]
This seems like an issue with your connector not knowing the Avro schema when it tries to deserialize the record. I recommend using a schema registry for serialization/deserialization. Also, can you test with bin/kafka-console-producer and consumer to make sure that the connector works with byte array serialization?

**Comment by emy-lee** [comment]
> This seems like an issue with your connector not knowing the Avro schema when it tries to deserialize the record. I recommend using a schema registry for serialization/deserialization. Also, can you test with bin/kafka-console-producer and consumer to make sure that the connector works with byte array serialization?

I get the same error with kafka-console-producer.
Any idea?

**Comment by jmwilli25** [comment]
@emy-lee I'm thinking that the Avro record is still in the topic. Try these steps:

1) Create a new topic, different from `my-test`
2) Produce to the topic with the console producer (not avro)
3) Consumer from the topic with the console consumer (not avro)
4) Turn on the elasticsearch connector

If there is an error from the connector post the error here.

**Comment by emy-lee** [comment]
@jmwilli25 I still get the same error. How is this possible?
I stopped connect, created a new topic my-test10, produced something in that topic with kafka-console-producer, consumed with kafka-console-consumer, turned on elasticsearch connector and I get the same error.

This is my config:

```
curl http://localhost:8083/connectors/elasticsearch-sink
{"name":"elasticsearch-sink","config":{"connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector","type.name":"kafka-connect","elastic.https.ssl.truststore.type":"JKS","connection.password":"xxx","tasks.max":"1","topics":"my-test10","connection.username":"elastic","plugin.path":"/home/xxx/confluent-community-5.3.1/share/plugins/confluentinc-kafka-connect-elasticsearch-5.3.1","key.ignore":"true","elastic.https.ssl.protocol":"TLS","name":"elasticsearch-sink","elastic.security.protocol":"SSL","elastic.https.ssl.truststore.password":"xxx","connection.url":"https://xxx:9200","elastic.https.ssl.truststore.location":"/home/xxx/confluent-community-5.3.1/xxx.server.truststore.jks"},"tasks":[{"connector":"elasticsearch-sink","task":0}],"type":"sink"}
```

**Comment by levzem** [comment]
hi @emy-lee, please see my response to #353

**Comment by levzem** [comment]
Closing this due to no response - please free to reopen if you have any further questions
