### ISSUE TITLE
This elasticsearch connector doesn't send any data to the elasticsearch. Why?

### ISSUE THREAD

**Issue by xciaoatuttix** [confluentinc/kafka-connect-elasticsearch#353]
Can anyone tell me why is there no data in the my-test3 topic and in the index of elasticsearch?

```
$ curl http://localhost:8083/connectors/
["elasticsearch-sink"]

$ curl http://localhost:8083/connectors/elasticsearch-sink/
{"name":"elasticsearch-sink","config":{"connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector","type.name":"kafka-connect","elastic.https.ssl.truststore.type":"JKS","connection.password":"xxx","tasks.max":"1","topics":"my-test3","connection.username":"elastic","plugin.path":"/home/xxx/confluent-community-5.3.1/share/plugins/confluentinc-kafka-connect-elasticsearch-5.3.1","key.ignore":"true","internal.key.converter.schemas.enable":"false","value.converter.schema.registry.url":"http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081","internal.key.converter":"org.apache.kafka.connect.json.JsonConverter","elastic.https.ssl.protocol":"TLS","internal.value.converter.schemas.enable":"false","name":"elasticsearch-sink","internal.value.converter":"org.apache.kafka.connect.json.JsonConverter","elastic.security.protocol":"SSL","elastic.https.ssl.truststore.password":"password","connection.url":"https://xxx:9200","value.converter":"io.confluent.connect.avro.AvroConverter","key.converter":"io.confluent.connect.avro.AvroConverter","key.converter.schema.registry.url":"http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081","elastic.https.ssl.truststore.location":"/home/xxx/confluent-community-5.3.1/my.server.truststore.jks"},"tasks":[{"connector":"elasticsearch-sink","task":0}],"type":"sink"}

$ curl http://localhost:8083/connectors/elasticsearch-sink/status
{"name":"elasticsearch-sink","connector":{"state":"RUNNING","worker_id":"127.0.0.1:8083"},"tasks":[{"id":0,"state":"RUNNING","worker_id":"127.0.0.1:8083"}],"type":"sink"}

```

The topic has been created:
```
bin/kafka-topics --list --zookeeper localhost:2181
...
my-test
my-test2
my-test3
...


$ bin/kafka-avro-console-producer --broker-list localhost:9092 --topic my-test3 --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
{"f1": "111"}
{"f1": "222"}
```

```
$ bin/kafka-avro-console-consumer --bootstrap-server localhost:9092 --topic my-test3 --from-beginning
{"f1": "111"}
{"f1": "222"}
```

I tryed to connect to this page with the browser to see if it create the index: https://xxx:9200/_cat/indices?v
```
health status index        uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   my-test2 xxxxxxxxxxxxxxxxxxxxxxxxx   1   1          0            0       283b           283b
yellow open   my-test3 xxxxxxxxxxxxxxxxxxxxxxxxx   1   1          0            0       230b           230b
yellow open   my-test  xxxxxxxxxxxxxxxxxxxxxxxxx   1   1          0            0       283b           283b
```

**Comment by xciaoatuttix** [comment]
When I write something in the topic, then I get this in the status of the connector:

`$ curl http://localhost:8083/connectors/elasticsearch-sink/status
{"name":"elasticsearch-sink","connector":{"state":"RUNNING","worker_id":"127.0.0.1:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"127.0.0.1:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:487)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error: \n\tat org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:344)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:487)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)\n\t... 13 more\nCaused by: org.apache.kafka.common.errors.SerializationException: java.io.CharConversionException: Invalid UTF-32 character 0xc90b7375 (above 0x0010ffff) at char #1, byte #7)\nCaused by: java.io.CharConversionException: Invalid UTF-32 character 0xc90b7375 (above 0x0010ffff) at char #1, byte #7)\n\tat com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:195)\n\tat com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:158)\n\tat com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:243)\n\tat com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2339)\n\tat com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:656)\n\tat com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4043)\n\tat com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2572)\n\tat org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:45)\n\tat org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:342)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:487)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:487)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"}],"type":"sink"}[`

**Comment by levzem** [comment]
@xciaoatuttix the problem is that you are using an avro producer which serializes using avro, but your connector is configured to use the JsonConverter to deserialized records in json. Those two are not compatible. Please either use a different producer or change your connector configs `key.converter` and `value.converter` to the appropriate AvroConverter

**Comment by levzem** [comment]
Closing this due to no response - please free to reopen if you have any further questions
