### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by dabr-grapeup** [confluentinc/kafka-connect-elasticsearch#355]
We're trying to push 5MB/s through connector and we have an issue with it. The delay in ElasticSearch is increasing and we're not sure what can be a cause. We're using default values for connector, we've tested it with lower throughput (2,5MB/s) and it works without any problems. 

Our Kafka messages are around 10KB each and topic is compressed with lz4, has 6 partitions distributed on 3 Kafka instances. 
Our Kafka connect cluster consists of 6 nodes each has 2 CPUs and 2,5GB memory. Max heap size is set to 2GB. Connector has 6 tasks.

Do you have any recommendation or an idea what can be a limitation?

**UPDATE:**
We did different test: two connectors reading from different topics with messages rate at 2MB/s and they worked without any problems and were able to ingest data to ElasticSearch with rate 4MB/s. Each connector had 6 tasks. It leads to conclusion that either we're missing something in configuration of connector or single connector isn't able to handle such traffic.

**Comment by levzem** [comment]
@dabr-grapeup 

A connector can only handle so much throughput. 5 MB/s sound like quite a bit. 2 MB/s sounds pretty reasonable. There are many variables that contribute to its performance (i.e network). There are several configs that you can tune to scale the connector.

`batch.size`
`max.in.flight.requests`
`tasks.max`

after that the only, adding more connectors is the only way to scale

**Comment by dabr-grapeup** [comment]
@levzem thank you for your answer! :)
