### ISSUE TITLE
[Question] RefreshPolicy when indexing 

### ISSUE THREAD

**Issue by dkirrane** [confluentinc/kafka-connect-elasticsearch#362]
How does the Connector write to Elasticsearch. Is there a config option to set the Refresh Policy like in the Elasticsearch Rest High Client API? Does it use this under the hood?

https://static.javadoc.io/org.elasticsearch/elasticsearch/7.0.1/org/elasticsearch/action/support/WriteRequest.RefreshPolicy.html#WAIT_UNTIL

**Comment by levzem** [comment]
The connector uses the Jest client under the hood. The refresh policy is supported by the ES client and not the Jest client. Looking through the code, the only time our connector calls `refresh()` is during testing, so we follow the default behavior described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html). The Jest client will close the request after it is received regardless of any refresh policy.
