### ISSUE TITLE
Problem with SYNC kafka to elasticSinkConnector

### ISSUE THREAD

**Issue by patsadow2** [confluentinc/kafka-connect-elasticsearch#367]
Hello,

I've got werid problem. 

Kafka send data to elastic only when i POST connectors, (mssql -> kafka works great) (kafka -> elastic) not :(

This is my conf. i use 5.3.2 and elk 7.2.0
```
{
	  "name": "es-sink-user",
	  "config": {
		"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
		"tasks.max": "1",
		"topics": "user",
		"connection.url": "http://elasticsearch:9200",
		"transforms": "unwrap,key",
		"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
		"transforms.unwrap.drop.tombstones": "false",
		"transforms.unwrap.drop.deletes": "false",
		"transforms.key.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
		"transforms.key.field": "id",
        "key.ignore": "true",
        "schema.ignore": "true",
		"type.name": "_doc",
		"behavior.on.null.values": "delete"
	  }
}

```

From logs i see only:
```
2019-12-29 11:25:11,303 INFO   ||  WorkerSourceTask{id=inventory-connector-0} Committing offsets   [org.apache.kafka.connect.runtime.WorkerSourceTask]
2019-12-29 11:25:11,303 INFO   ||  WorkerSourceTask{id=inventory-connector-0} flushing 0 outstanding messages for offset commit   [org.apache.kafka.connect.runtime.WorkerSourceTask]
```

Is it some kind of flag to pass to get sync every time (kafka->elastic) ? What could be wrong ?

**Comment by ncliang** [comment]
The logs you posted are from a source connector and probably unrelated. Elasticsearch connector here is a sink connector. Try look in your logs for occurrence of `WorkerSinkTask`, your connector name `es-sink-user`, something about elasticsearch like `ElasticsearchSink` or `ElasticsearchClient`, or anything that looks like a warning or an error (`WARN` or `ERROR`).

Here is also some more documentation and a quickstart to help you get started: 
https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/index.html

**Comment by cricket007** [comment]
The logs should show connector and consumer config objects being loaded for the sync task

But, note: Connect defaults to read messages from the latest offsets of a topic, so if you're not producing data, nothing will be in Elasticsearch

**Comment by patsadow2** [comment]
It sync after query elastic.
