### ISSUE TITLE
Could not build kafka-connect-elasticsearch through maven.

### ISSUE THREAD

**Issue by nvelumani** [confluentinc/kafka-connect-elasticsearch#368]
Hello Team,

I downloaded Kafka-connect-elastic search and tried building it through maven following the steps in the given link (https://sematext.com/blog/kafka-connect-elasticsearch-how-to/)

I get the below error can anyone please help with the error  ? or please let me know where I can find instructions to install it properly thanks. 

-------------------------------------------------------------------------------
Test set: io.confluent.connect.elasticsearch.ElasticsearchSinkTaskTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 sec <<< FAILURE! - in io.confluent.connect.elasticsearch.ElasticsearchSinkTaskTest
io.confluent.connect.elasticsearch.ElasticsearchSinkTaskTest  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.elasticsearch.ElasticsearchSinkTestBase
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:585)

**Comment by nvelumani** [comment]
The issue was solved by skipping the test.

PS: Ran "mvn clean package-DskipTests" instead "mvn clean package"

**Comment by mgnisia** [comment]
you have to run `mvn clean package -DskipTests` just for clarification
