### ISSUE TITLE
Ignoring version conflicts for items causes loss of data

### ISSUE THREAD

**Issue by adrianotr** [confluentinc/kafka-connect-elasticsearch#374]
We noticed this issue after our Elasticsearch data got corrupted. We checked the topics and the data was not matching.

When reading from multiple topics and using the UPSERT write strategy, there is a high chance that update conflicts will happen on Elasticsearch. The current logic ignores any update conflicts reported by Elasticsearch, leading to data loss.
```
WARN Ignoring version conflicts for items: [Key{index_v3/_doc/US725754}] (io.confluent.connect.elasticsearch.jest.JestElasticsearchClient)
```

I can think of three possible solutions to this:

1. Retry on the server side by using [retry_on_conflict](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#docs-update-api-query-params).
This is an easy and efficient approach. It might be a good idea to add a configuration parameter to enable the user to set how many update retries they want to allow, but even a hard set number of retries (as bellow) is a better default than missing updates and ending up with corrupt data. 
To add the retry we can change this code:
```
// JestElasticsearchClient.java
private Update toUpdateRequest(IndexableRecord record) {
    String payload = "{\"doc\":" + record.payload
        + ", \"doc_as_upsert\":true}";
    return new Update.Builder(payload)
        .index(record.key.index)
        .type(record.key.type)
        .id(record.key.id)
        .setParameter("retry_on_conflict", 5)  // here: including the server retry query parameter
        .build();
  }
```

2. Retry on the client side using the existing retry logic. 
In this case it might be a good idea to filter the batch items to only include the conflicting documents.
To do that we have to modify the existing logic in `JestElasticsearchClient.executeBulk(BulkRequest)`, because it currently ignores update conflicts.

3. Assign the same partition numbers (from different topics) to the same connector Task.
This way no concurrency issues would happen, UNLESS there are other applications writing to the same index. I am not sure, but this does not look like a trivial implementation.

**Comment by levzem** [comment]
@adrianotr this looks like a good contribution you could make.

I like option 2 the most as it is the easiest and cleanest to implement and leverages ES's api. 

How do you feel about opening a PR to address this?

**Comment by adrianotr** [comment]
I was checking the code change to implement option 2, but it seems a much more involved change, because we would have to change how the retry is implemented (unless we retry the whole bulk again). Also, sending another request increases the possibility of more conflicts.

It seems that, since we already pass the Map with the configuration parameters in the JestElasticsearchClient constructor, it should be very simple to add a parameter `retry.on.conflict` and include that in the request as I've shown in option 1.

Let me know what you think. I can add a PR then.

**Comment by adrianotr** [comment]
I created https://github.com/confluentinc/kafka-connect-elasticsearch/pull/384

**Comment by LeonardoBonacci** [comment]
Any update on this issue?
