### ISSUE TITLE
ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception

### ISSUE THREAD

**Issue by sudarshanGit** [confluentinc/kafka-connect-elasticsearch#379]
I am trying to start my elastic search sink connector in distributed mode.
My quickstart-elasticsearch.properties
`name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=3
topics=fsp-audit
key.ignore=true
connection.url=https://***
type.name=kafka-connect
errors.tolerance = all
errors.deadletterqueue.topic.name = fsp-dlq-audit-event`

My connect-standalone.properties

```
`bootstrap.servers=**:9092,***:9092,***:9092
group.id=connect-cluster
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.topic=connect-offsets
offset.storage.replication.factor=1
schema.enabled=false
config.storage.topic=connect-configs
config.storage.replication.factor=1
status.storage.topic=connect-status
status.storage.replication.factor=1
offset.flush.interval.ms=10000
plugin.path=/usr/local/confluent/share/java`
```

I start my connector like below
 
```
/usr/local/confluent/bin/kafka-rest-start /usr/local/confluent/etc/kafka-rest/kafka-rest.properties

/usr/local/confluent/bin/connect-distributed /usr/local/confluent/etc/kafka/connect-distributed.properties

curl  -X POST -H "Content-Type: application/json" --data '{"name":"elastic-search-sink-audit","config":{"connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector","tasks.max":"2","topics":"fsp-AUDIT_EVENT_DEMO","key.ignore":"true","connection.url":"https://***.amazonaws.com","type.name":"kafka-connect","name":"elastic-search-sink-audit","errors.tolerance":"all","errors.deadletterqueue.topic.name":"fsp-dlq-audit-event"}}' http://localhost:8083/connectors | jq
```

after hitting this is get 

{
  "error_code": 500,
  "message": "Request timed out"
}

i am using elastic search 6.0 and confluent 5.4.0

I am able to start my kafka connect in stand alone mode ..

**Comment by levzem** [comment]
Hi @sudarshanGit, can you please provide more information? There is not to go off on.

Are you able to confirm that Connect and Kafka are running correctly before trying to start the connector?

**Comment by levzem** [comment]
Closing due to no response. Please feel free to reopen if you are still having issues.
