### ISSUE TITLE
Skip "Failed to execute batch" exception

### ISSUE THREAD

**Issue by ragian** [confluentinc/kafka-connect-elasticsearch#380]
I'm getting the following error in the kafka elasticsearch sink because the indexes "index_XXX_2018-02" and "index_XXX_2018-01" are closed (and I'm not able to reopen it).

` WARN Failed to execute batch 245 of 500 records with attempt 5/6, will attempt retry after 100681 ms. Failure reason: Bulk request failed: [{"type":"index_closed_exception","reason":"closed","index_uuid":"MBEQZTyCSKSwEolBzExBYw","index":"index_XXX_2018-02"}, {"type":"index_closed_exception","reason":"closed","index_uuid":"jmiSrG5qRiiPXubYh9O_TQ","index":"index_XXX_2018-01"}]`

They are very old retry because we had in the connector configuration these settings:
`
 "max.retries": "5",
"retry.backoff.ms": "10000",
`
Is there a way to skip these kind of error (now each time a connector gets one of that error, it crashes). I have tried to setting 
`
behavior.on.malformed.documents=ignore
`
but doesn't work (the task continues to crash).
Any suggest?

**Comment by levzem** [comment]
@ragian unfortunately there is no way to avoid this failure. The connector will retry a set amount of time and fail if it does not achieve a successful write.

A workaround you can do is use an SMT to transform the topic name to redirect the records to a different (open) index.
