### ISSUE TITLE
Misconfiguring Connector Leads to NullPointerException in getServerVersion

### ISSUE THREAD

**Issue by davis-x** [confluentinc/kafka-connect-elasticsearch#386]
I'm interested why https://github.com/confluentinc/kafka-connect-elasticsearch/issues/350 was closed. In the case where you've misconfigured the kafka connector, it's not really useful to get a `NullPointerException` in `getServerVersion` and then have to figure out "oh I didn't set the right security.protocol". 

In my case I was using the wrong username and password. I think a better behavior would have been to get an error relating to "unable to connect" or "invalid credentials" or something. Getting a `NullPointerException` and then having to search github issues to try and identify if it was something I did incorrectly or a bug in the connector doesn't seem very user friendly. At a minimum I think the code should check something and raise a more friendly error message rather then letting a NullPointerException bubble out.

**Comment by levzem** [comment]
@davis-x I agree. This seems like a good improvement. Do you want to issue a PR to address? I will happily review it.

**Comment by levzem** [comment]
#394 addresses this issue
