### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by fhalim** [confluentinc/kafka-connect-elasticsearch#39]
The current master HEAD (0b590cddf12a6a18725dfee3f791a22b358913db) does not build. It depends on SNAPSHOT versions of the Confluent Platform libraries (3.2.0-SNAPSHOT) and Kafka (0.10.2.0-SNAPSHOT), neither of which are available on [the public repository](http://packages.confluent.io/maven/).

**Comment by ewencp** [comment]
Please see [this FAQ] which explains the details of this and includes a branch you can use to build against an 0.10.0.0 released version of Kafka.

**Comment by bowlofstew** [comment]
Is it a common software practice to have a master branch in a state that doesn't compile?  Also you FAQ markdown is busted.  Would you care to update as I would like to build as well.
