### ISSUE TITLE
Using ElasticsearchSinkConnector to read data from topic having different "types"

### ISSUE THREAD

**Issue by sandhyabakash** [confluentinc/kafka-connect-elasticsearch#392]
I am trying to work with Elasticsearch connector and wanted to know if there is a way I can read data off a kafka topic that has different types of records and then be able forward them to different elastic indices via a single connector instance ? Or would I need to necessarily have different connectors setup, one for each type ?

**Comment by levzem** [comment]
@sandhyabakash I would need more specific examples by what you mean different types of records, but what you are describing does not sound possible. It sounds like you will need different connectors. Ideally, a topic contains consistent data.

You can apply some SMTs which change the topic based on your records and thus reroute the records to different indices, however, I do not know your use case.

**Comment by sandhyabakash** [comment]
Let's say I have records of type "Address", "Food", "Vehicle", "Animal" all coming into a single topic say "all-topic". 
So are you suggesting, that I can create my own transformer wherein as I read the incoming records, I can create a new ConnectRecord by setting it to an appropriate topic such that it gets written to the collection with the same name as that of the topic ?

**Comment by levzem** [comment]
@sandhyabakash in that case, yes a custom SMT seems to best solve your use case.

**Comment by sandhyabakash** [comment]
Thank you @levzem . I am closing this incident for now.
