### ISSUE TITLE
NullPointerException: JestElasticsearchClient.getServerVersion

### ISSUE THREAD

**Issue by akshaymhetre** [confluentinc/kafka-connect-elasticsearch#394]
Hi, I am trying to test my Kafka connector config with elasticsearch on AWS. While doing this I got following exception :

java.lang.NullPointerException
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.getServerVersion(JestElasticsearchClient.java:231)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:142)

I am using kafka-connect 5.4.0 docker image. Here is the connector config:

{
  "name": "events-elasticsearch-sink",
  "config": {
    "connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "elastic.security.protocol": "SSL",
    "tasks.max": "1",
    "topics": "KAFKA_TOPIC",
    "key.ignore": "true",
    "connection.url": "https://....aws.com",
    "type.name": "mvp-audit-trail",
    "name": "events-elasticsearch-sink",
    "transforms":"InsertMessageTime,ConvertTimeValue,RouteTS",
    "transforms.InsertMessageTime.type": "org.apache.kafka.connect.transforms.InsertField$Value",
    "transforms.InsertMessageTime.timestamp.field": "connector_processing_timestamp",
    "transforms.ConvertTimeValue.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
    "transforms.ConvertTimeValue.target.type":"Timestamp",
    "transforms.ConvertTimeValue.field":"timestamp",
    "transforms.ConvertTimeValue.format": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
    "transforms.RouteTS.type":"org.apache.kafka.connect.transforms.TimestampRouter",
    "transforms.RouteTS.topic.format":"${topic}-${timestamp}",
    "transforms.RouteTS.timestamp.format":"yyyy-MM-dd"
  }
}
 
This has been tested locally and was working fine. However, when I am trying to connect to AWS ES. We are facing this issue.

Connect service is running inside a Pod and has all access to Elasticsearch. To validate the access, I ran Python script given [here](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html). Python script is able to create and read index in elasticsearch.

Could you please help with this?

**Comment by akshaymhetre** [comment]
Is this issue related with this [PR](https://github.com/confluentinc/kafka-connect-elasticsearch/pull/330)?

**Comment by levzem** [comment]
@akshaymhetre  we do not support AWS ES at this point
