### ISSUE TITLE
topic.index.map is ignored on record put

### ISSUE THREAD

**Issue by bsiamionau** [confluentinc/kafka-connect-elasticsearch#40]
According to documentation, `topic.index.map` config defines mapping between Kafka topics and Elasticsearch indices. I have the following map configured: `topic.index.map=mytopic:myindex`, so I expect records from `mytopic` to be added to `myindex`. But in `io.confluent.connect.elasticsearch.ElasticsearchWriter#write` method I see another behavior - topic name is used for schema mapping, despite the fact that mapped index name was used during initialization and index creation. So I always receive __index_not_found_exception__ in `io.confluent.connect.elasticsearch.Mapping#createMapping` as long as I have index `myindex`, but connector is trying to find `mytopic` one. Quick fix solved this issue for me:

    String mappedIndex = topicToIndexMap.get(sinkRecord.topic());
    final String index = mappedIndex != null ? mappedIndex : sinkRecord.topic();

...but I'm not sure if I've got the idea of the given config correctly and using it in a proper way. Could you kindly check if it's bug or not?

Thanks

**Comment by shikhar** [comment]
This does appear to be a bug, thank you for reporting.
