### ISSUE TITLE
topic.key.ignore not works as expceted 

### ISSUE THREAD

**Issue by suikast42** [confluentinc/kafka-connect-elasticsearch#402]
Hi, 

I pushed the json underneath  as config over kafka-connect rest

`{
  "auto.create.indices.at.start": false,
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "connection.url": "http://elasticsearch:9200",
  "connection.timeout.ms": 5000,
  "read.timeout.ms": 5000,
  "tasks.max": "5",
  "topics": "filebeat, metricbeat, logstatistics",
  "schema.ignore": true,
  "key.ignore": false,
  "topic.key.ignore": "filebeat, metricbeat",
  "flush.timeout.ms":60000,
  "max.retries":42,
  "retry.backoff.ms": 100,
  "max.in.flight.requests": 5,
  "max.buffered.records":20000,
  "batch.size":4096,
  "drop.invalid.message": true,
  "name": "elasticsearch-ecs-connector",
  "type.name": "_doc",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schemas.enable": "false",
  "transforms":"routeTS",
  "transforms.routeTS.type":"org.apache.kafka.connect.transforms.TimestampRouter",
  "transforms.routeTS.topic.format":"${topic}-${timestamp}",
  "transforms.routeTS.timestamp.format":"YYYY.MM.dd",
  "errors.tolerance": "all" ,
  "errors.log.enable": false ,
  "errors.log.include.messages": false,
  "errors.deadletterqueue.topic.name":"logstream-dlq",
  "errors.deadletterqueue.context.headers.enable":true ,
  "errors.deadletterqueue.topic.replication.factor": 1
}`

my excpectations is that filebat and metricbeat indices should ignore the keys but logstatistics not. 

But kafla-connect says  ERROR Can't convert record from topic/partition/offset filebeat-2020.04.19/3/262036. Error message: Key is used as document id and can not be null. (io.confluent.connect.elasticsearch.ElasticsearchWriter)
 ans it's right ther is no key :-D. 

I am using ElasticSearch 7.6.2
Confluent Platform 5.4.1
Everything in sdocker of course ;-)

**Comment by levzem** [comment]
@sandeep-vunet, @suikast42  you are using an SMT to transform the topic therefore you are seeing this issue. please set `key.ignore` to `true` if you are using SMTs that change the topic

**Comment by sandeep-vunet** [comment]
@levzem  Hey no without using SMT also i facing this same issue.
```
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=metricbeat
auto.create.indices.at.start=false
key.ignore=false
topic.key.ignore='metricbeat'
connection.url=http://10.0.14.6:9200
type.name=doc
flush.timeout.ms=100000
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
schema.ignore=true 
```
With above configuration also getting same error.
