### ISSUE TITLE
Connector compatible Java version and SLF4J API implementation

### ISSUE THREAD

**Issue by cipriandumitrel** [confluentinc/kafka-connect-elasticsearch#406]
Hi guys,

We are trying to start the Kafka ElasticSearch Sink connector in a Docker container within Kubernetes. For that we are using confluentinc/cp-kafka-connect-base docker image and applying 
`
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch
` afterwards. 

However, as far as I can see there are no such images that rely on Java 11. Am I right? Only images with Java 8 are supported? 

Moreover, is there a possibility to integrate Logback instead of Log4j?

Thanks a lot!

**Comment by levzem** [comment]
@cipriandumitrel we only support Java8. For Logback, I don't know what the integration level is with Kafka but you would have to configure that on the Kafka side. However I dont think it supports anything but Log4j
