### ISSUE TITLE
Document id changed when changing record topic with transformation

### ISSUE THREAD

**Issue by michaelfortin** [confluentinc/kafka-connect-elasticsearch#416]
I'm trying to move data from kafka to elasticsearch. I also want the index in which data is written to to depend on the message content. So I tried using transformation like RegexRouter or ExtractTopic to change the record topic. It works, but the problem is the document_id created also change according to the new record topic. 

My config
```
{
    "name": "my_connector",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "name": "my_connector",
        "tasks.max": "1",
        "topics": "the_actual_topic",
        "key.ignore": "true",
        "schema.ignore": "true",
        "type.name": "kafka-connect",
        "connection.url": "elasticsearch_url",
        "transforms": "router",
        "transforms.router.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.router.regex": "(.*)",
        "transforms.router.replacement": "kakaka"
    }
}
```

The message are correctly written to the index `kakaka` but their `document_id` become 
`kakaka+<partition>+<offset>` 
which is quite a problem. I would like the document_id to stay
`<actual topic name>+<partition>+<offset>`

Result document example in Elasticsearch
```
{
    "_index": "kakaka",
    "_type": "kafka-connect",
    "_id": "kakaka+0+4",
    "_score": 1.0,
    "_source": {
        "value": "roger"
    }
}
```

**Comment by levzem** [comment]
@michaelfortin unfortunately it is not possible to keep the old topic name as part of the ID unless you use SMTs to change the record key to contain the original topic name along with some other unique identifying information and set `key.ignore=false`

**Comment by levzem** [comment]
closing due to no reply, feel free to reopen if you still need help
