### ISSUE TITLE
Unknown magic byte even with AvroConverter

### ISSUE THREAD

**Issue by slimaneakalia** [confluentinc/kafka-connect-elasticsearch#424]
Hello, I got this error after restarting the elastic search sink connector. 
`
org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic topic_name to Avro:  at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:110) at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86) Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte! 
`

The problem is that the data was written using a JDBC source connector with:
```
value.converter = class io.confluent.connect.avro.AvroConverter
```
And the schema was registered on the schema registry.

The weird thing is that I wasn't getting the error before restart (I'm using an incremental JDBC source connector to keep data up to date).
Here is the es sink connector config.

```JSON
{
  "name": "es-sink-connector-name",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "transforms.extractAdId.field": "rec_id",
    "transforms.extractAdId.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
    "type.name": "recs",
    "behavior.on.null.values": "delete",
    "tasks.max": "6",
    "topics": "topic_name",
    "transforms": "extractAdId,removeCurrentState",
    "max.retries": "30",
    "transforms.removeCurrentState.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
    "flush.timeout.ms": "60000",
    "name": "es-sink-connector-name",
    "transforms.removeCurrentState.blacklist": "current_state",
    "connection.url": "http://elasticsearch"
  }
}
```

**Comment by levzem** [comment]
@slimaneakalia this means that you have a record in your topic that was not serialized by the `AvroConverter` and therefore it is unable to deserialize it using the `AvroConverter`. Try using another converter like `Byte`, `String`, or `Json`

**Comment by OskarsPakers** [comment]
I ran into the same issue
``Internal Server Error: Failed to convert argument [offsets] for value [null] due to: Cannot deserialize value of type `int` from String "local": not a valid Integer value`
Tried on dev version and it is not reproducible.
