### ISSUE TITLE
How to extract from the source data field as the ID of elasticsearch？

### ISSUE THREAD

**Issue by shenzgang** [confluentinc/kafka-connect-elasticsearch#426]
How to extract from the source data field as the ID of es, I want to perform upsert operation according to my ID, otherwise the automatically generated ID is always unique, so how do I update my record?

**Comment by levzem** [comment]
@shenzgang [look into single message transforms (SMTs)](https://docs.confluent.io/current/connect/transforms/index.html). The connector uses the key to generate the ID (configuration `key.ignore=false`, so as long as you can get the record key to be what you want, you can update the document.
