### ISSUE TITLE
Build failure due to incorrect Kafka version in pom.xml

### ISSUE THREAD

**Issue by matthew-d-jones** [confluentinc/kafka-connect-elasticsearch#43]
Maven failed on missing dependencies due to the `-rc1` version suffix being appended to the version number for Kafka itself in `pom.xml`. This should be straightforward to fix and avoid others wasting as much time as me.

**Comment by ewencp** [comment]
Which branch are you trying to build? I don't think we have any branches with any `rc1` versions in the pom file. There's a release candidate tag that relies on a `-cp1` version of Kafka, but this is pretty clearly labeled as a release candidate and those will sometimes rely on yet-unpublished dependencies as we build & test the platform as a whole, then push the release.

**Comment by matthew-d-jones** [comment]
When I download something from releases, whether it is a release candidate or not, I expect it to be buildable. Looking back at closed issues I see that others have had this problem. May I suggest at least adding a note to the README to check the Kafka version in `pom.xml` exists?

**Comment by bquartier** [comment]
Hi @ewencp, 

Thank you for your reply. 
As others, I was also a little bit confused by the branch / tag and the fact that mast doesn't compile if you only have access to the public confluent repository. 
Could you please give us more information about the below points?
 - will the jar be released and published?
 - are you planning to tag the code corresponding to the release kafka version (which tag should I use with Kafka 10.1?)?

This connector looks great, thank you for your work.

**Comment by ewencp** [comment]
@matthew-d-jones There has not been an official release yet. We have opened up the repository early to allow people to have an early look. We provided the `0.10.0.0` branch on this repository to help those out who didn't want to build the SNAPSHOT dependencies themselves.

@bquartier Yes, the jars will be released and published, both in packaged form with the rest of Confluent and in Maven, although generally you'll want the former as it'll have all the dependencies bundled with it. We tag our releases of our projects with the version of Confluent that we release it with, i.e. you will see a `v3.1.0` tag when we generate the 3.1.0 release.

**Comment by matthew-d-jones** [comment]
@ewencp Ok, thank you. It is working nicely and we appreciate the work of the developers and Confluent making it available.

**Comment by bquartier** [comment]
@matthew-d-jones were you able to make it work in distributed mode?
I keep getting an error saying:
org.apache.kafka.connect.errors.ConnectException: Sink tasks require a list of topics.

How did you define the mapping between topic and ES indices?
I tried a lot of different format in topic.index.map, without success.

**Comment by matthew-d-jones** [comment]
@bquartier I've only tried the standalone connector so far, but that error suggests that you have not specified which topics to use in the .properties file. My `elasticsearch-kafka-connect.properties` file looks like this:
```
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
connection.url=http://localhost:9200
type.name=kafka-connect
# Custom config
topics=sample_log_test
key.ignore=true
```

**Comment by bquartier** [comment]
@matthew-d-jones thanks.
Cannot make it work in distributed mode. Don't know how to translate the topic=sample_log_test. Will open a new issue as I suspect there may be a but somewhere.

**Comment by sreekanthkarakula** [comment]
is there any solution if the above error occurs in distriburted mode?

**Comment by levzem** [comment]
Closing because there are official releases of the connector now. Please reopen if there are any questions.
