### ISSUE TITLE
connector fails and stop inexplicably

### ISSUE THREAD

**Issue by mdespriee** [confluentinc/kafka-connect-elasticsearch#438]
(UPDATED for clarity)

I have an Elastic connector configured as follows:
```
{
        "name":"legacy-measures-elastic-sink",
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "connection.url": "https://redacted.aws.cloud.es.io:9243",
        "connection.username": "redacted",
        "connection.password": "redacted",
        "topics": "dsp-measures",
        "type.name": "_doc",
        "key.ignore": "false",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "schema.ignore": "true",
        "write.method": "upsert",
        "batch.size": "500",
        "transforms": "partitioner",
        "transforms.partitioner.type": "org.apache.kafka.connect.transforms.TimestampRouter",
        "transforms.partitioner.topic.format": "${topic}-${timestamp}",
        "transforms.partitioner.timestamp.format": "YYYY-MM",
        "errors.tolerance": "all",
        "errors.log.enable": "true", 
        "errors.log.include.messages": "true",    
        "tasks.max": "3",
        "max.retries": "100",
        "behavior.on.malformed.documents": "warn"
}
```
And this connector failed (despite the error tolerance and retries, and so on) with 
```
Task threw an uncaught and unrecoverable exception.
org.apache.kafka.common.errors.WakeupException
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:511)
[...]
```

I have no other exception around that may explain this. 
(The only others I have are exception due to the connector stopping `BulkProcessor.throwIfStopping`)

I finally managed to resume the connector work by restarting and re-pushing the same configuration several times (I known this sounds very much like an IT-crowd joke ¯\_(ツ)_/¯), and I struggle to understand what's going on here. 

Any idea ? How can I diagnose this further ? How can I prevent it ?

kafka-connect version=5.5.0

**Comment by mdespriee** [comment]
I realize the exception I added is "throwIfStopping" so it's not the cause of the problem. I really have no clue of what's going on here.

**Comment by levzem** [comment]
@mdespriee `WakeupException` indicates an underlying Kafka issues

**Comment by levzem** [comment]
closing due to no reply, feel free to reopen if you are still experiencing issues
