### ISSUE TITLE
Shield Auth Support

### ISSUE THREAD

**Issue by michaeltravisuk** [confluentinc/kafka-connect-elasticsearch#45]
Is there support for HTTP authentication with an Elasticsearch cluster protected by Shield?

If not, is there a way of handling the authentication elsewhere, i.e. an Elasticsearch client node or similar?

**Comment by shikhar** [comment]
I'm afraid we don't support Shield authentication or HTTPS currently from the connector itself. We'd definitely like to add that.

> If not, is there a way of handling the authentication elsewhere, i.e. an Elasticsearch client node or similar?

It's possible to have a plain->secure HTTP proxy in the middle, I haven't looked into the mechanics or whether such a setup can be made secure.

**Comment by ave19** [comment]
Just dropping a note, +1.  Our environment requires authentication and HTTPS.  Organizations that use the Elastic stack operationally will buy support, probably, and enable the X Pack plugins which require these features to connect.  (Also, Elastic Cloud Enterprise.)  We have developers in house who could work on something like this.  Did you have any plan for implementation?  I know adding PKI bits is a lot of infrastructure.

**Comment by sscarduzio** [comment]
+1 

You mentioned you want to add this, but Is there a timeline?

**Comment by PrimeAC** [comment]
+1

**Comment by ZeluisFS** [comment]
+1

**Comment by sscarduzio** [comment]
I ended up starting to implement this myself. See #111

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/kafka-connect-elasticsearch/pull/215
