### ISSUE TITLE
Optional type.name config param

### ISSUE THREAD

**Issue by drTr0jan** [confluentinc/kafka-connect-elasticsearch#451]
Types are deprecated in APIs in 7.0 - [Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html).
But `type.name` config param is still mandatory. I'm trying to create the connector without the param and get the error:
```
Connector configuration is invalid and contains the following 1 error(s):
Missing required configuration "type.name" which has no default value.
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
```

**Comment by smart-shore** [comment]
Hello , you can config the type name with _doc ，and  I have already try it and it works
Just like  the below image
![image](https://user-images.githubusercontent.com/49391727/95813902-88935f80-0d4b-11eb-956d-3593f13a92b0.png)
![image](https://user-images.githubusercontent.com/49391727/95813964-bc6e8500-0d4b-11eb-9774-263dd7e5a729.png)

**Comment by drTr0jan** [comment]
@smart-shore, thx. It's wrote about it at the comments in `io.confluent.connect.elasticsearch.jest.actions`.
