### ISSUE TITLE
Facing version conflict on insert with key.ignore set to the default 'FALSE'

### ISSUE THREAD

**Issue by aalmangour** [confluentinc/kafka-connect-elasticsearch#485]
Dear All,

Thank you for this amazing connector, I appreciate all the efforts.
I'm facing a version conflict error while trying to index a topic using the message key, I guess this is because it will enable the external versioning on ES. But it seems that it's not retreiving the kafkaOffset correctly for some reason.

The error that I'm geeting is:
`WARN Ignoring version conflict for operation INDEX on document '2021-01-04T19:45:24.000ZA6.166' version -1 in index 'enrichment-test-final2-2021-01-04'. (io.confluent.connect.elasticsearch.ElasticsearchClient:392)`

And the configuration is:
```
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
transforms=routeTS,ValueToKey,extractKey
transforms.routeTS.topic.format=${topic}-${timestamp}
transforms.extractKey.type=org.apache.kafka.connect.transforms.ExtractField$Key
value.converter=io.confluent.connect.avro.AvroConverter
errors.log.enable=true
key.converter=org.apache.kafka.connect.storage.StringConverter
transforms.ValueToKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.extractKey.field=message_id
topics=enrichment-test-final2
transforms.routeTS.type=org.apache.kafka.connect.transforms.TimestampRouter
transforms.ValueToKey.fields=message_id
transforms.routeTS.timestamp.format=YYYY-MM-DD
value.converter.schema.registry.url=http://192.168.0.194:8081,http://192.168.0.195:8081
name=elastic-confluent7
errors.tolerance=all
connection.url=http://192.168.0.81:9200,http://192.168.0.98:9200,http://192.168.0.99:9200,http://192.168.0.103:9200,http://192.168.0.104:9200
```

**Comment by emiling** [comment]
@aalmangour 

I faced same problem with this, so how did you solve it?

**Comment by aalmangour** [comment]
Hi @emiling 
The error is legit, and no problem is there.

It's happening because multiple documents having the same ID are being indexed, that's why this error happens.

**Comment by Harish-Sridhar** [comment]
Hi @aalmangour 

But what if we want to have the last document with the same ID overwrite all the previous documents instead of erroring out due to version conflict? How do we achieve that?

**Comment by polakr** [comment]
I had some luck with write.method=UPSERT. It was able to process through the version error. But you have to check if it suits your use case (effect is partial update instead of full replace). It also probably is not fixing the root cause of the problem.

**Comment by younesDev00** [comment]
I am facing the same issue, any ideas on a fix, i have upsert set to true and when i upsert from topic A into index Users with some id it works, then if i attempt to upsert the same document with the same ID from topic B into the same index (users) it wont work throwing version conflicts
