### ISSUE TITLE
kafka es connector 

### ISSUE THREAD

**Issue by ramimohammad** [confluentinc/kafka-connect-elasticsearch#505]
When I try to run >> curl -i -X POST -H "Accept:application/json"     -H  "Content-Type:application/json" http://localhost:8083/connectors/     -d @es.json

es.json 

  {
    "name": "elastic-sink",
    "config": {
      "connector.class":
          "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
      "tasks.max": "1",
      "topics": "preserver.public.freelancer_freelancer",
      "connection.url": "http://10.0.11.145:9200",
      "transforms": "unwrap,key",
      "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",        
      "transforms.key.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
      "transforms.key.field": "id",                                                 
      "key.ignore": "false",                                                        
      "type.name": "_freelancers"                                                       
    }
  }

I got this error , I spent the whole day searching : 

javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.Server.handle(Server.java:505)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at java.base/java.lang.Thread.run(Thread.java:834)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]: Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:436)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         ... 28 more
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at io.confluent.connect.elasticsearch.Validator.<init>(Validator.java:56)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at io.confluent.connect.elasticsearch.ElasticsearchSinkConnector.validate(ElasticsearchSinkConnector.java:79)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:318)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:672)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:669)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:299)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:248)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Mar 08 15:58:58 ip-10-0-11-161 connect-distributed[4831]:         ... 1 more

**Comment by ramimohammad** [comment]
Now I fixed the previous error , but new error appears 

[2021-03-09 09:41:43,492] WARN /connectors/ (org.eclipse.jetty.server.HttpChannel:597)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.StackOverflowError
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.Server.handle(Server.java:505)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.lang.Thread.run(Thread.java:834)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]: Caused by: org.glassfish.jersey.server.ContainerException: java.lang.StackOverflowError
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:436)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         ... 28 more
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]: Caused by: java.lang.StackOverflowError
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.lang.String.indexOf(String.java:1578)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.lang.String.indexOf(String.java:1535)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:143)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/sun.net.www.protocol.file.Handler.parseURL(Handler.java:67)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.net.URL.<init>(URL.java:674)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.net.URL.<init>(URL.java:541)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1219)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:314)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:455)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.security.AccessController.doPrivileged(Native Method)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:96)
Mar 09 09:41:43 ip-10-0-11-161 connect-distributed[2604]:         at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:389)

**Comment by ramimohammad** [comment]
now this issue Mar 11 08:23:13 ip-10-0-11-10 connect-distributed[3806]: [2021-03-11 08:23:13,126] ERROR Plugin class loader for connector: 'io.confluent.connect.elasticsearch.ElasticsearchSinkConnector' was not found. Returning: org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader@69930714 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:165)

**Comment by levzem** [comment]
@ramimohammad that is a Connect issue, not ES connector issue, closing, but feel free to reopen if you are still having issues
