### ISSUE TITLE
Kafka Connect ES Sink - Question about the malformed documents, logging and dead letter queues

### ISSUE THREAD

**Issue by Harish-Sridhar** [confluentinc/kafka-connect-elasticsearch#508]
We are using the following kafka connect and ES Sink versions:
```
Kafka-connect: 6.1.0
kafka-connect-elasticsearch: 11.0.0
```

We use the following properties in the job configurations.
```
  "behavior.on.malformed.documents": "WARN",
  "errors.tolerance": "all",
  "errors.log.enable":true,
  "errors.log.include.messages":true,
  ```
  
  I expected that whenever a document is rejected by ES (ie malformed document) we will have the message that was rejected logged to the console.
  But it didn't happen. Below are log snippets:
  ```
2021-03-25 05:55:27,370] WARN Encountered an illegal document error 'ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=object mapping for [<field_name>] tried to parse field [<field_name>] as object, but found a concrete value]]'. Ignoring and will not index record. (io.confluent.connect.elasticsearch.ElasticsearchClient)
```
No logs regarding the event..

Below are my questions:

1. When ES rejects a document, can the actual event be logged? if so how?
2. When ES rejects a document, can the event be sent to dead letter queue? if so will it work if deal letter queue properties are set or something else should happen?

**Comment by levzem** [comment]
@Harish-Sridhar if you check, the connector actually puts these records in a dlq
https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java#L389-L393
https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java#L498-L501

using the [ErrantRecordReporter from KIP-610](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors), which you can configure if you would like to see your bad records
