### ISSUE TITLE
Support dynamic selection of index per message

### ISSUE THREAD

**Issue by barakm** [confluentinc/kafka-connect-elasticsearch#549]
It would be useful to have a plugin mechanism which will allow custom code to run and select the ElasticSearch index/alias where a message should be written to.

In my scenario, the target index is calculated based on a combination of the information in the message, in dynamic configuration (something like Consul) and possibly even cached information periodically loaded from a database.

I considered doing this with some sort of custom SMT, but I don't want to transform the message in anyway - I just need to read it so I can resolve the correct index (all indices are in the same cluster).

**Comment by levzem** [comment]
You can use an SMT i.e RegexRouter to rename the topic of the message because the index is just the topic name. Transforming the Kafka record does not affect it in the topic. The SMT sits between Kafka and the connector and will only alter what the connector sees.

**Comment by barakm** [comment]
Yes, that makes way more sense. Thanks for pointing this out!
