### ISSUE TITLE
Ignoring invalid task provided

### ISSUE THREAD

**Issue by murali-krishnamoorthy** [confluentinc/kafka-connect-elasticsearch#585]
Hi i am getting the following error. [2021-09-28 02:15:00,867] WARN WorkerSinkTask{id=sink_order_ordersdb_elastic_v1.OrderData-1} Ignoring invalid task provided offset cdc_OrderData-3/OffsetAndMetadata{offset=28983, leaderEpoch=null, metadata=''} -- partition not assigned, assignment=[cdc_ordersdb.orders.OrderData-2, cdc_ordersdb.orders.OrderData-3] (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2021-09-28 02:15:00,867] WARN WorkerSinkTask{id=s

I am using the latest stable version . ( confluentinc-kafka-connect-elasticsearch-11.1.2.zip)  Here is my connector configuration.

{
    "name": "sink_order_ordersdb_elastic_v1.OrderData",
    "config": {
      "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
      "topics": "cdc_ordersdb.orders.OrderData",
      "tasks.max": "5",
  
      "connection.url": "url for elastic removed for security reasons",
      "connection.username": " removed for security reasons",
      "connection.password": " removed for security reasons",
  
      "transforms": "unwrap,dropPrefix",
      "transforms.unwrap.type": "io.debezium.connector.mongodb.transforms.ExtractNewDocumentState",
      "transforms.unwrap.drop.tombstones": "false",
      "transforms.unwrap.delete.handling.mode": "drop",
  
      "transforms.dropPrefix.regex": "(.*)\\.(.*)\\.(.*)",
      "transforms.dropPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
      "transforms.dropPrefix.replacement": "cdc_$3",
  
      "errors.log.enable": "true",
      "errors.tolerance": "all",
      "errors.log.include.messages": "true",
      "errors.deadletterqueue.topic.name": "__deadletter.sink_order_ordersdb_elastic_v1.OrderData",
      "errors.deadletterqueue.topic.replication.factor": "3",
      "errors.deadletterqueue.context.headers.enable": "true",
  
      "value.converter.schemas.enable": "true",
      "value.converter": "io.confluent.connect.avro.AvroConverter",
      "value.converter.schema.registry.url": "schema registry url",
      "key.converter.schemas.enable": "false",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  
      "behavior.on.null.values": "DELETE",
      "behavior.on.malformed.documents": "WARN",
      "write.method": "UPSERT",
  
      "key.ignore": "false",
      "schema.ignore": "false",
      "consumer.override.max.partition.fetch.bytes":"20971520"
  
    }
  }

**Comment by murali-krishnamoorthy** [comment]
Additional note when it switched to  version kafka-connect-elasticsearch-11.1.0 i no longer have this issue , may be something introduced after that

**Comment by erdody** [comment]
Thanks for reporting @murali-krishnamoorthy . 
I see that the invalid offset belongs to topic `cdc_OrderData`, but the connector configuration (and the current assignment) points to topic `cdc_ordersdb.orders.OrderData`. Is it possible that the connector configuration was changed?
Also, do you see this WARN message regularly?

**Comment by murali-krishnamoorthy** [comment]
hi sorry i was playing around with the names , but the issue still exists and i see a warn message a lot. one interesting think i noted is when i was using the kafka offset explorer tool to look for consumers the consumer is flagged as inactive , but not sure who its still able to read .

**Comment by murali-krishnamoorthy** [comment]
Hi that is issue . 

Here is message : [2021-09-30 03:17:28,187] WARN [sink_order_ordersdb_elastic_OrderHeaderData|task-3] WorkerSinkTask{id=sink_order_ordersdb_elastic_OrderHeaderData-3} Ignoring invalid task provided offset cdc_OrderHeaderData-3/OffsetAndMetadata{offset=104199, leaderEpoch=null, metadata=''} -- partition not assigned, assignment=[cdc_ordersdb.orders.OrderHeaderData-3] (org.apache.kafka.connect.runtime.WorkerSinkTask:430)

Configuration 
curl -X PUT \
  /api/Order-Sink-Cluster/connectors/sink_order_ordersdb_elastic_OrderHeaderData/config \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -d '{
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "errors.log.include.messages": "true",
  "behavior.on.null.values": "DELETE",
  "transforms.unwrap.delete.handling.mode": "drop",
  "connection.password": "${awssecret:/tfcom/kafka-connect/secrets:kafka.connect.elastic.password}",
  "tasks.max": "10",
  "transforms": "unwrap,extractKey,dropPrefix",
  "transforms.dropPrefix.regex": "(.*)\\.(.*)\\.(.*)",
  "key.ignore": "false",
  "transforms.extractKey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
  "errors.deadletterqueue.context.headers.enable": "true",
  "transforms.unwrap.drop.tombstones": "false",
  "write.method": "UPSERT",
  "errors.deadletterqueue.topic.replication.factor": "3",
  "transforms.unwrap.type": "io.debezium.connector.mongodb.transforms.ExtractNewDocumentState",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "errors.log.enable": "true",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "read.timeout.ms": "60000",
  "transforms.dropPrefix.replacement": "cdc_$3",
  "transforms.extractKey.field": "id",
  "topics": "cdc_ordersdb.orders.OrderHeaderData",
  "batch.size": "2000",
  "connection.username": "${awssecret:/tfcom/kafka-connect/secrets:kafka.connect.elastic.user}",
  "transforms.dropPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
  "schema.ignore": "true",
  "behavior.on.malformed.documents": "WARN",
  "value.converter.schema.registry.url": "https://tfcom-kafka-connect-schema-registry.tfcom-cluster-na-commerceqa1.cloudqa.thermofisher.net",
  "key.converter.schemas.enable": "true",
  "errors.deadletterqueue.topic.name": "__deadletter_sink_order_ordersdb_elastic_OrderHeaderData",
  "value.converter.schemas.enable": "true",
  "errors.tolerance": "all",
  "consumer.override.max.partition.fetch.bytes": "20971520",
  "connection.url": "https://search-tfcom-order-history-qa1-mnzzhqvhgikjivqzka4rjl54l4.us-east-1.es.amazonaws.com",
  "key.converter.schema.registry.url": "https://tfcom-kafka-connect-schema-registry.tfcom-cluster-na-commerceqa1.cloudqa.thermofisher.net"
}'

and i have also a
<img width="1769" alt="Screen Shot 2021-09-29 at 11 18 57 PM" src="https://user-images.githubusercontent.com/56832545/135380800-b8d771fd-a4dd-4563-8e37-751c87f08fba.png">
ttached the image of kafka consumer

**Comment by murali-krishnamoorthy** [comment]
This issue exists in both 11.1.1 and 11.1.2 where no consumer is actually getting created on the broker end , it works fine in 11.1.0

**Comment by erdody** [comment]
Thanks for the information @murali-krishnamoorthy 

Unfortunately, there seems to be a limitation in connectors that override preCommit: they can't use SMTs that alter the topic name, they only get the converted topic names and there's no translation back in the framework when it validates the offsets information coming from preCommit. This also affects S3 Sink and other connectors.

The Elasticsearch Sink connector started overriding preCommit since 11.1.2.

**Comment by gasiorroiasg** [comment]
we have experiencing the same issue. 
am i missing something? it seems that overriding preCommit has broken major feature of transformations. 
is there other way now to change destination topics on the fly? if not is it planned to bring this functionality back?

**Comment by mmarchiore** [comment]
@gasiorroiasg did you find a workaround for this?

**Comment by erdody** [comment]
@gasiorroiasg @mmarchiore we just released a new version (11.1.4) with a new "[synchronous flushing](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java#L118)" mode that would be compatible with topic-mutating SMTs.
We also created [KIP-793](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=191336830) to add formal support for this in the framework, which once approved and merged, will have to be leveraged by each connector.

**Comment by mmarchiore** [comment]
thanks @erdody it works with the new version

**Comment by erdody** [comment]
Thanks for the confirmation @mmarchiore . Closing.
