### ISSUE TITLE
Drop invalid record if needed

### ISSUE THREAD

**Issue by patsak** [confluentinc/kafka-connect-elasticsearch#66]
Hi! 
Sink task has failed if data converter throws exception:
https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java#L209-L211
Sometimes is very usefull to drop this kind of messages and write error in log.
Is it possible to add option to change task behaviour in this situation?

**Comment by pradeepkusingh** [comment]
yes, I am looking for this feature.

**Comment by ewencp** [comment]
Fixed in #91 thanks to the original reporter, @patsak. Thanks again!
