### ISSUE TITLE
Transform Lat Lon to GeoPoint

### ISSUE THREAD

**Issue by toabey** [confluentinc/kafka-connect-elasticsearch#70]
Is it possible to transform from { Lat: valLat, Lon:valLon, name:placeName} to {name:placeName, Location : {Lat:valLat,Lon:valLon} } format using single message transform with this plugin.
 I tried this ....
transforms=hoistToStruct
transforms.hoistToStruct.type=org.apache.kafka.connect.transforms.HoistField$Value
transforms.hoistToStruct.field=Location

It works 
, the problem is record transformed to {Location:  {name:placeName,Lat:valLat,Lon:valLon} } which is not what I want.

**Comment by levzem** [comment]
@toabey unfortunately at this time we do not have anything like that but by using multiple transforms you might be able to achieve this effect

**Comment by levzem** [comment]
closing but feel free to reopen with further questions
