### ISSUE TITLE
Create a daily index

### ISSUE THREAD

**Issue by stefanofrigerio** [confluentinc/kafka-connect-elasticsearch#71]
I'm thinking about a dynamic index creation. The current cfg mapping is
`topicname -> indexname (auto infer ES mapping)`

What I need is something like that

`topicname -> indexname-YYYYMMDD (template mapping indexname-* )`

it is a sort of daily sharding of data, useful for dashboarding a huge set of infos. The data are essentially facts, so yesterday data won't be updated and consequently reindexed after midnight.

the field I intend to use for the index creation is the timestamp in the kafka message, so reprocessing data will be solid and safe.

**Comment by superwhykz** [comment]
Agree this feature will be useful!  One of the solution you can do it is recreate connects via cron job but that kind of lame to do that.

**Comment by ewencp** [comment]
You might be able to accomplish this with [single message transformations](http://kafka.apache.org/documentation/#connect_transforms), specifically the `TimestampRouter`. It will replace the topic name with the format you're suggesting. Does this work for you?

**Comment by superwhykz** [comment]
@ewencp thanks so much on following up on this!  After defining ` topic.format `  do i need to make any changes in  `topic.index.map`?

**Comment by superwhykz** [comment]
It did not work for us. 

```
"transforms" : "MyRouter",
"transforms.MyRouter.type" : "org.apache.kafka.connect.transforms.TimestampRouter",
"transforms.MyRouter.topic.format" : "${topic}-${timestamp}",
"transforms.MyRouter.timestamp.format" : "yyyyMMddHH",
...
```

**Comment by golanig** [comment]
Also, it will be great if the timestamp will be taken from the body of the message itself. Some use cases are that the logs are retrieved in delay.

**Comment by superwhykz** [comment]
Wanted to update on this. We were able to roll rotation after we specified version 0.10 in filebeat. It seems filebeat defaults to 0.9 if no version specified. It seems v.10 can transform timestamp from filebeat otherwise it defaults to epoch or something.   This is how our connect looks:

```
{
  "name": "???",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "type.name": "true",
    "transforms.MessageTypeRouter.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.TimestampRouter.timestamp.format": "yyyy.MM.dd.HH",
    "tasks.max": "1",
    "topics": "???,???,???,???",
    "transforms": "MessageTypeRouter, TimestampRouter",
    "key.ignore": "true",
    "schema.ignore": "true",
    "transforms.TimestampRouter.topic.format": "${topic}-${timestamp}",
    "flush.timeout.ms": "30000",
    "transforms.MessageTypeRouter.replacement": "???",
    "name": "???",
    "transforms.TimestampRouter.type": "org.apache.kafka.connect.transforms.TimestampRouter",
    "connection.url": "http://elasticsearch:9200",
    "transforms.MessageTypeRouter.regex": "???"
  },
  "tasks": [
    {
      "connector": "???",
      "task": 0
    }
  ]
}
```

**Comment by yuancheng-p** [comment]
Maybe a gentle reminder: we also need to enable the timestamp config in the kafka cluster `log.message.timestamp.type=LogAppendTime`.

**Comment by ewencp** [comment]
@superwhykz Glad you worked it out. @yuancheng-p good point that if you are not producing with a client that fills in timestamps, you will want `LogAppendTime`.

Since it seems the issue was sorted out, I'm going to close this. Feel free to reopen if you're still having an issue.

**Comment by stefanofrigerio** [comment]
@ewencp it still doesn't work, but the behaviour we are experimenting seems more like a bug. The timestamp router works fine, but the indexes aren't created. https://github.com/confluentinc/kafka-connect-elasticsearch/issues/152

**Comment by gopikrishna967** [comment]
Sharing a solution that worked for me: #33

**Comment by shiveshsky** [comment]
@golanig were you able to create indexes in elasticsearch based data from logs?

**Comment by levzem** [comment]
closing this because solutions have been offered with SMTs
