### ISSUE TITLE
Could not create index on elasticsearch

### ISSUE THREAD

**Issue by totojack** [confluentinc/kafka-connect-elasticsearch#78]
Hi.

We have this error trying to run connector 3.1.1 and elasticsearch 5.3 (from official ES docker):

org.apache.kafka.connect.errors.ConnectException: Could not create index:MEASM-TOPIC at io.confluent.connect.elasticsearch.ElasticsearchWriter.createIndicesForTopics(ElasticsearchWriter.java:251) at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.open(ElasticsearchSinkTask.java:113) at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:431) at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1000(WorkerSinkTask.java:55) at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:467) at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:228) at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:313) at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:277) at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:259) at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979) at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:317) at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:235) at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172) at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

This is the connector configuration:

{
"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
"type.name": "kafka-connect",
"tasks.max": "1",
"topics": "MEASM-TOPIC",
"name": "ElasticsearchSinkConnector",
"key.ignore": "true",
"connection.url": "http://elasticsearch:9200"
}

It seems the problems is on the specific topic. We tried with another new test topic and connector didn't throw any exception: index on elastic was correctly created and data moved from kafka to elastic. The stack trace didn't give explanation on the cause of the problem.

Thanks
Luca

**Comment by abandin-stratio** [comment]
I have the very same issue. In my case i think its beacause i use Xpack with authentication, and this kafka connector doenst support this kind of access. I will have to try logstash...

**Comment by atomic77** [comment]
I was hitting the same problem and eventually realized it was because Elasticsearch doesn't accept upper-case index names - especially tedious if your source data is a db that really wants to make everything upper case!

**Comment by levzem** [comment]
That is in fact the reason for the error. The exception method has been update to be more descriptive.

Closing this, but feel free to reopen if you have any additional questions?
