### ISSUE TITLE
mapper_parsing_exception with string records containing json

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-elasticsearch#82]
I am seeing this upon indexing any record into ES:

```
[BulkProcessor@2073013577-1] WARN io.confluent.connect.elasticsearch.bulk.BulkProcessor - Failed to execute batch 1 of 1 records, retrying after 100 ms
org.apache.kafka.connect.errors.ConnectException: Bulk request failed: [{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}]
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:353)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:326)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:312)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I want the connector to take the incoming payloads (which are string encoded json) and index them as is into ES, so I have set `schema.ignore=true` and `value.converter.schemas.enable=false`. I've added some debug info to see what is going wrong and noticed the payload that the ES connector ultimately indexes looks like this:

`"{\"entry_point\": \"rabbitmq\", \"ts_posted\": \"2017-04-05T02:02:27.296757\", \"tracer_id\": \"eb1c8284-19a3-11e7-9555-0a7b84c6deb8\"}`

The original value in the SinkRecord is a non-escaped String containing the json data, i.e.

`{"entry_point": "rabbitmq", "ts_posted": "2017-04-05T02:02:27.296757", "tracer_id": "eb1c8284-19a3-11e7-9555-0a7b84c6deb8"}`

ES expects this to be a JSON payload without escaping.
While debugging, I wrote a unit test to reproduce this. In ElasticsearchWriterTest, the test looks like this:

```
  @Test
  public void testWriterIgnoreSchemaStringRecord() throws Exception {
    final boolean ignoreKey = true;
    final boolean ignoreSchema = true;

    String value = "{\"foo\":\"bar\"}";
    Collection<SinkRecord> records = Collections.singletonList(new SinkRecord(TOPIC, PARTITION, Schema.STRING_SCHEMA, key, Schema.STRING_SCHEMA, value, 0));
    ElasticsearchWriter writer = initWriter(client, ignoreKey, ignoreSchema);
    writeDataAndRefresh(writer, records);
    verifySearchResults(records, ignoreKey, ignoreSchema);
  }
```

I dug further in the code and I believe the issue comes from this line: https://github.com/confluentinc/kafka-connect-elasticsearch/blob/ff0d381578d808f2d3be332c21bc679da9dfa6e4/src/main/java/io/confluent/connect/elasticsearch/DataConverter.java#L99

When the JsonConverter is passed a string as a value and no schema, it will end up returning an escaped json string. It seems like if the value in the SinkRecord is already a string, and there is no schema or schemas are ignored, it should not use the JsonConverter?

**Comment by xiaobai5150** [comment]
In confluent worker config properties, make value.converter=org.apache.kafka.connect.json.JsonConverter  ，it will change the the kafka SinkRecord in json converter ,JSON_CONVERTER.fromConnectData will work.

**Comment by levzem** [comment]
closing because #95 addresses the solution to the issue
