### ISSUE TITLE
Error during maven build

### ISSUE THREAD

**Issue by tslater** [confluentinc/kafka-connect-elasticsearch#84]
I tried finding a pre-built .jar, but wasn't able to find one. Is there one available?

**Comment by ewencp** [comment]
The easiest way to get the connector is to [download Confluent Platform](https://www.confluent.io/download/). It is included in both the open source and enterprise downloads. It is already packaged so you can just download, extract, and execute Connect and the plugin will be ready to use.

The artifact you were missing should be available in Confluent's maven repository, and this project is setup to use it automatically. It's possible you had a temporary connectivity issue, in which case trying to rebuild with `-U` will try refetching the jar.

You can also get the pre-built jars for this connector in that repository, but they are not uberjars so you'd need to resolve the dependencies. The repository information is available [in our installation instructions](There are instructions for setting it up here: http://docs.confluent.io/current/installation.html#installation-maven).
