### ISSUE TITLE
documents going under docs.deleted with key.ignore as true

### ISSUE THREAD

**Issue by deeptiantony** [confluentinc/kafka-connect-elasticsearch#86]
Hi There, 

I am trying to load data from a kafka topic to elasticsearch index with key.ignore=true. But on elasticsearch, I see docs.deleted counts getting increased/decreased but still docs.count seems to be perfect. Am I missing something here? I understand that with lucene updations take place as delete+insert. But with key.ignore set to true, these should not happen. It would be really great if you can help me understand. 

Thanks,
Deepti

**Comment by levzem** [comment]
@deeptiantony are you still having these issues?

**Comment by levzem** [comment]
closing due to lack of response but feel free to reopen if you are still having this issue
