### ISSUE TITLE
How to use this connect !??

### ISSUE THREAD

**Issue by lynchlee** [confluentinc/kafka-connect-elasticsearch#87]
Could someone can tell user how to use this connect, use as a plugin , use as an application or other ??
I think we need provide a simple readme , should we ??

**Comment by mtak** [comment]
The documentation should get you a long way: http://docs.confluent.io/current/connect/connect-elasticsearch/docs/elasticsearch_connector.html

**Comment by RobGThai** [comment]
I'm learning this connect via this [blog](https://sematext.com/blog/2017/03/06/kafka-connect-elasticsearch-how-to)

**Comment by ewencp** [comment]
As @mtak mentioned, the documentation for the connector should get you a long way. If you're new to Kafka Connect, you'll probably want to start with the general [quickstart](http://docs.confluent.io/current/connect/quickstart.html) and [documentation](http://docs.confluent.io/current/connect/intro.html).

I'm going to close this as I don't think there's much to follow up on here other than pointing you towards the documentation, but feel free to reopen if there's some follow up.
