### ISSUE TITLE
Build?

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-elasticsearch#9]
Hi,
I'm keen to try this connector out. I cloned the repo and ran `mvn clean package` but hit a failure 

```
Failed to execute goal on project kafka-connect-elasticsearch: 
Could not resolve dependencies for project io.confluent:kafka-connect-elasticsearch:jar:3.1.0-SNAPSHOT: 
The following artifacts could not be resolved: 
org.apache.kafka:connect-api:jar:0.10.1.0-SNAPSHOT, 
org.apache.kafka:connect-json:jar:0.10.1.0-SNAPSHOT: 
Could not find artifact org.apache.kafka:connect-api:jar:0.10.1.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/) 
```

I'm new to building packages etc, but happy to give it a go :) - can you point me towards how I can resolve these dependencies? Thanks!

**Comment by Ishiihara** [comment]
@rmoff Thanks for trying this out. The elasticsearch connector depends on Kafka trunk. You can first checkout Kafka trunk and run `./gradlew install` to install Kafka in local maven repo.

**Comment by Ishiihara** [comment]
@rmoff FYI, we just created a 0.10.0.0 branch that builds against the 0.10.0.0 release of Kafka. You can checkout that branch and run `mvn clean package -DskipTests` to build the connector.
