### ISSUE TITLE
Support multiple types

### ISSUE THREAD

**Issue by yuancheng-p** [confluentinc/kafka-connect-elasticsearch#98]
Hello, is there any plan to support multiple types of kafka messages from one single topic?

It can be handled by copying the type from the structured kafka message to the `_type` meta field while indexing into elasticsearch.

Using the `_type` acts like name-spacing the messages in the elasticsearch and each type of data can therefore have its own mapping (which can be dynamic). This will resolve the mapping conflict problem while indexing. 

This feature would be very appreciated because it will allow us to add new types of messages without doing any modification in the configuration of this connector nor in the elasticsearch.

**Comment by BDeus** [comment]
The _type will be deprecated in the next version of elasticsearch

https://github.com/elastic/elasticsearch/issues/15613
https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch

**Comment by yuancheng-p** [comment]
@BDeus yes you are right, the `_type` of the elasticsearch is actually confusing and does not provide the namespace for fields in different types.
